// GENERATED by gen_l10n_test.ps1 - smoke test for every localized string.
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sagen/l10n/app_localizations.dart';

void main() {
  const locales = <Locale>[
    Locale('es'),
    Locale('en'),
    Locale('fr'),
    Locale('pt'),
  ];
  for (final locale in locales) {
    test('todas las cadenas de ${locale.languageCode} no vacias', () {
      final l = lookupAppLocalizations(locale);
      expect(
        l.achievementConqueror,
        isNotEmpty,
        reason: 'achievementConqueror',
      );
      expect(
        l.achievementConquerorDesc,
        isNotEmpty,
        reason: 'achievementConquerorDesc',
      );
      expect(l.achievementConstant, isNotEmpty, reason: 'achievementConstant');
      expect(
        l.achievementConstantDesc,
        isNotEmpty,
        reason: 'achievementConstantDesc',
      );
      expect(l.achievementCurious, isNotEmpty, reason: 'achievementCurious');
      expect(
        l.achievementCuriousDesc,
        isNotEmpty,
        reason: 'achievementCuriousDesc',
      );
      expect(
        l.achievementCyberGuardian,
        isNotEmpty,
        reason: 'achievementCyberGuardian',
      );
      expect(
        l.achievementCyberGuardianDesc,
        isNotEmpty,
        reason: 'achievementCyberGuardianDesc',
      );
      expect(
        l.achievementDigitalMaster,
        isNotEmpty,
        reason: 'achievementDigitalMaster',
      );
      expect(
        l.achievementDigitalMasterDesc,
        isNotEmpty,
        reason: 'achievementDigitalMasterDesc',
      );
      expect(
        l.achievementDigitalStudent,
        isNotEmpty,
        reason: 'achievementDigitalStudent',
      );
      expect(
        l.achievementDigitalStudentDesc,
        isNotEmpty,
        reason: 'achievementDigitalStudentDesc',
      );
      expect(
        l.achievementDigitalWeek,
        isNotEmpty,
        reason: 'achievementDigitalWeek',
      );
      expect(
        l.achievementDigitalWeekDesc,
        isNotEmpty,
        reason: 'achievementDigitalWeekDesc',
      );
      expect(
        l.achievementFirstShield,
        isNotEmpty,
        reason: 'achievementFirstShield',
      );
      expect(
        l.achievementFirstShieldDesc,
        isNotEmpty,
        reason: 'achievementFirstShieldDesc',
      );
      expect(l.achievementGuardian, isNotEmpty, reason: 'achievementGuardian');
      expect(
        l.achievementGuardianDesc,
        isNotEmpty,
        reason: 'achievementGuardianDesc',
      );
      expect(l.achievementLearner, isNotEmpty, reason: 'achievementLearner');
      expect(
        l.achievementLearnerDesc,
        isNotEmpty,
        reason: 'achievementLearnerDesc',
      );
      expect(
        l.achievementLegendaryStreak,
        isNotEmpty,
        reason: 'achievementLegendaryStreak',
      );
      expect(
        l.achievementLegendaryStreakDesc,
        isNotEmpty,
        reason: 'achievementLegendaryStreakDesc',
      );
      expect(l.achievementLocked, isNotEmpty, reason: 'achievementLocked');
      expect(l.achievementPerfect, isNotEmpty, reason: 'achievementPerfect');
      expect(
        l.achievementPerfectDesc,
        isNotEmpty,
        reason: 'achievementPerfectDesc',
      );
      expect(l.acquired, isNotEmpty, reason: 'acquired');
      expect(l.analyzeLink, isNotEmpty, reason: 'analyzeLink');
      expect(l.appName, isNotEmpty, reason: 'appName');
      expect(l.authBack, isNotEmpty, reason: 'authBack');
      expect(l.authCanceled, isNotEmpty, reason: 'authCanceled');
      expect(l.authCreateAccount, isNotEmpty, reason: 'authCreateAccount');
      expect(l.authDefault, isNotEmpty, reason: 'authDefault');
      expect(
        l.authDeleteAccountFailed,
        isNotEmpty,
        reason: 'authDeleteAccountFailed',
      );
      expect(l.authEmailError, isNotEmpty, reason: 'authEmailError');
      expect(l.authEmailInUse, isNotEmpty, reason: 'authEmailInUse');
      expect(l.authEmailInvalid, isNotEmpty, reason: 'authEmailInvalid');
      expect(l.authEmailLabel, isNotEmpty, reason: 'authEmailLabel');
      expect(l.authEnterEmailError, isNotEmpty, reason: 'authEnterEmailError');
      expect(l.authFacebookButton, isNotEmpty, reason: 'authFacebookButton');
      expect(l.authFacebookError, isNotEmpty, reason: 'authFacebookError');
      expect(
        l.authFirebaseUnavailable,
        isNotEmpty,
        reason: 'authFirebaseUnavailable',
      );
      expect(
        l.authForgotPasswordButton,
        isNotEmpty,
        reason: 'authForgotPasswordButton',
      );
      expect(
        l.authForgotPasswordDesc,
        isNotEmpty,
        reason: 'authForgotPasswordDesc',
      );
      expect(
        l.authForgotPasswordTitle,
        isNotEmpty,
        reason: 'authForgotPasswordTitle',
      );
      expect(l.authGoogleButton, isNotEmpty, reason: 'authGoogleButton');
      expect(l.authGoogleError, isNotEmpty, reason: 'authGoogleError');
      expect(
        l.authInvalidCredential,
        isNotEmpty,
        reason: 'authInvalidCredential',
      );
      expect(l.authInvalidEmail, isNotEmpty, reason: 'authInvalidEmail');
      expect(l.authLoginButton, isNotEmpty, reason: 'authLoginButton');
      expect(l.authLoginError, isNotEmpty, reason: 'authLoginError');
      expect(l.authLoginTitle, isNotEmpty, reason: 'authLoginTitle');
      expect(l.authNetworkError, isNotEmpty, reason: 'authNetworkError');
      expect(l.authNoAccount, isNotEmpty, reason: 'authNoAccount');
      expect(
        l.authNotAuthenticated,
        isNotEmpty,
        reason: 'authNotAuthenticated',
      );
      expect(l.authNotFound, isNotEmpty, reason: 'authNotFound');
      expect(l.authNotVerified, isNotEmpty, reason: 'authNotVerified');
      expect(l.authNullToken, isNotEmpty, reason: 'authNullToken');
      expect(l.authNullUser, isNotEmpty, reason: 'authNullUser');
      expect(l.authPasswordError, isNotEmpty, reason: 'authPasswordError');
      expect(l.authPasswordLabel, isNotEmpty, reason: 'authPasswordLabel');
      expect(
        l.authPasswordMinError,
        isNotEmpty,
        reason: 'authPasswordMinError',
      );
      expect(l.authRateLimited, isNotEmpty, reason: 'authRateLimited');
      expect(l.authReauthError, isNotEmpty, reason: 'authReauthError');
      expect(
        l.authReauthRequiredForDelete,
        isNotEmpty,
        reason: 'authReauthRequiredForDelete',
      );
      expect(
        l.authRecoveryEmailSentDesc,
        isNotEmpty,
        reason: 'authRecoveryEmailSentDesc',
      );
      expect(
        l.authRecoveryEmailSentMessage,
        isNotEmpty,
        reason: 'authRecoveryEmailSentMessage',
      );
      expect(
        l.authRecoveryEmailSentTitle,
        isNotEmpty,
        reason: 'authRecoveryEmailSentTitle',
      );
      expect(l.authRecoveryError, isNotEmpty, reason: 'authRecoveryError');
      expect(
        l.authResendEmailError,
        isNotEmpty,
        reason: 'authResendEmailError',
      );
      expect(l.authSendEmailError, isNotEmpty, reason: 'authSendEmailError');
      expect(l.authSendLink, isNotEmpty, reason: 'authSendLink');
      expect(l.authTooManyRequests, isNotEmpty, reason: 'authTooManyRequests');
      expect(l.authUnknown, isNotEmpty, reason: 'authUnknown');
      expect(l.authVerifyError, isNotEmpty, reason: 'authVerifyError');
      expect(l.authWeakPassword, isNotEmpty, reason: 'authWeakPassword');
      expect(l.authWrongPassword, isNotEmpty, reason: 'authWrongPassword');
      expect(l.back, isNotEmpty, reason: 'back');
      expect(l.backButton, isNotEmpty, reason: 'backButton');
      expect(l.biometricReason, isNotEmpty, reason: 'biometricReason');
      expect(l.cancel, isNotEmpty, reason: 'cancel');
      expect(l.cancelButton, isNotEmpty, reason: 'cancelButton');
      expect(l.challengeComplete, isNotEmpty, reason: 'challengeComplete');
      expect(
        l.challengeCreatePassword,
        isNotEmpty,
        reason: 'challengeCreatePassword',
      );
      expect(l.challengeDetectRisk, isNotEmpty, reason: 'challengeDetectRisk');
      expect(l.challengeMiniCase, isNotEmpty, reason: 'challengeMiniCase');
      expect(l.challengeMultiple, isNotEmpty, reason: 'challengeMultiple');
      expect(l.challengeTrueFalse, isNotEmpty, reason: 'challengeTrueFalse');
      expect(
        l.challengeWhatWouldYouDo,
        isNotEmpty,
        reason: 'challengeWhatWouldYouDo',
      );
      expect(
        l.challenge_streak_milestone_title,
        isNotEmpty,
        reason: 'challenge_streak_milestone_title',
      );
      expect(l.gemMilestoneTitle, isNotEmpty, reason: 'gemMilestoneTitle');
      expect(l.chatBlocked, isNotEmpty, reason: 'chatBlocked');
      expect(l.chatCancel, isNotEmpty, reason: 'chatCancel');
      expect(l.chatClearAction, isNotEmpty, reason: 'chatClearAction');
      expect(l.chatClearMessage, isNotEmpty, reason: 'chatClearMessage');
      expect(l.chatClearTitle, isNotEmpty, reason: 'chatClearTitle');
      expect(l.chatEmptyTitle, isNotEmpty, reason: 'chatEmptyTitle');
      expect(
        l.chatFallbackSubtitle,
        isNotEmpty,
        reason: 'chatFallbackSubtitle',
      );
      expect(l.chatFallbackTitle, isNotEmpty, reason: 'chatFallbackTitle');
      expect(l.chatGuideSubtitle, isNotEmpty, reason: 'chatGuideSubtitle');
      expect(l.chatHint, isNotEmpty, reason: 'chatHint');
      expect(l.chatInputHint, isNotEmpty, reason: 'chatInputHint');
      expect(l.chatSageTutorLabel, isNotEmpty, reason: 'chatSageTutorLabel');
      expect(l.chestCollect, isNotEmpty, reason: 'chestCollect');
      expect(l.chestRewardDialog, isNotEmpty, reason: 'chestRewardDialog');
      expect(l.chestTapToOpen, isNotEmpty, reason: 'chestTapToOpen');
      expect(l.chestTypeBronze, isNotEmpty, reason: 'chestTypeBronze');
      expect(l.chestTypeGold, isNotEmpty, reason: 'chestTypeGold');
      expect(l.chestTypeLegendary, isNotEmpty, reason: 'chestTypeLegendary');
      expect(l.chestTypeSilver, isNotEmpty, reason: 'chestTypeSilver');
      expect(l.closeButton, isNotEmpty, reason: 'closeButton');
      expect(l.continueText, isNotEmpty, reason: 'continueText');
      expect(l.correct, isNotEmpty, reason: 'correct');
      expect(l.correctAnswer, isNotEmpty, reason: 'correctAnswer');
      expect(l.currencySymbol, isNotEmpty, reason: 'currencySymbol');
      expect(l.dayAbbrFri, isNotEmpty, reason: 'dayAbbrFri');
      expect(l.dayAbbrMon, isNotEmpty, reason: 'dayAbbrMon');
      expect(l.dayAbbrSat, isNotEmpty, reason: 'dayAbbrSat');
      expect(l.dayAbbrSun, isNotEmpty, reason: 'dayAbbrSun');
      expect(l.dayAbbrThu, isNotEmpty, reason: 'dayAbbrThu');
      expect(l.dayAbbrTue, isNotEmpty, reason: 'dayAbbrTue');
      expect(l.dayAbbrWed, isNotEmpty, reason: 'dayAbbrWed');
      expect(
        l.streakStatusCompleted,
        isNotEmpty,
        reason: 'streakStatusCompleted',
      );
      expect(l.streakStatusToday, isNotEmpty, reason: 'streakStatusToday');
      expect(l.streakStatusPending, isNotEmpty, reason: 'streakStatusPending');
      expect(l.daysLabel, isNotEmpty, reason: 'daysLabel');
      expect(l.delete, isNotEmpty, reason: 'delete');
      expect(l.deleteCloudData, isNotEmpty, reason: 'deleteCloudData');
      expect(l.demoModeLabel, isNotEmpty, reason: 'demoModeLabel');
      expect(l.demoStudentName, isNotEmpty, reason: 'demoStudentName');
      expect(l.emotionPhrase1, isNotEmpty, reason: 'emotionPhrase1');
      expect(l.emotionPhrase2, isNotEmpty, reason: 'emotionPhrase2');
      expect(l.emotionPhrase3, isNotEmpty, reason: 'emotionPhrase3');
      expect(l.emotionPhrase4, isNotEmpty, reason: 'emotionPhrase4');
      expect(l.emotionPhrase5, isNotEmpty, reason: 'emotionPhrase5');
      expect(l.emotionPhrase6, isNotEmpty, reason: 'emotionPhrase6');
      expect(l.emotionPhrase7, isNotEmpty, reason: 'emotionPhrase7');
      expect(l.emotionPhraseStart, isNotEmpty, reason: 'emotionPhraseStart');
      expect(l.emptyChatSubtitle, isNotEmpty, reason: 'emptyChatSubtitle');
      expect(l.emptyProfile, isNotEmpty, reason: 'emptyProfile');
      expect(l.emptyStore, isNotEmpty, reason: 'emptyStore');
      expect(
        l.errorContentLoadFailed,
        isNotEmpty,
        reason: 'errorContentLoadFailed',
      );
      expect(l.errorGeneric, isNotEmpty, reason: 'errorGeneric');
      expect(l.errorLoadQuestions, isNotEmpty, reason: 'errorLoadQuestions');
      expect(l.errorRestartApp, isNotEmpty, reason: 'errorRestartApp');
      expect(l.errorRetry, isNotEmpty, reason: 'errorRetry');
      expect(l.errorSomethingWrong, isNotEmpty, reason: 'errorSomethingWrong');
      expect(l.errorUnexpected, isNotEmpty, reason: 'errorUnexpected');
      expect(l.exitText, isNotEmpty, reason: 'exitText');
      expect(
        l.firstLessonSeeResults,
        isNotEmpty,
        reason: 'firstLessonSeeResults',
      );
      expect(
        l.flexCardJoinAlliance,
        isNotEmpty,
        reason: 'flexCardJoinAlliance',
      );
      expect(l.fontSizeLarge, isNotEmpty, reason: 'fontSizeLarge');
      expect(l.fontSizeNormal, isNotEmpty, reason: 'fontSizeNormal');
      expect(l.fontSizeSmall, isNotEmpty, reason: 'fontSizeSmall');
      expect(l.fontSizeTitle, isNotEmpty, reason: 'fontSizeTitle');
      expect(l.fontSizeXLarge, isNotEmpty, reason: 'fontSizeXLarge');
      expect(l.free, isNotEmpty, reason: 'free');
      expect(l.gems, isNotEmpty, reason: 'gems');
      expect(l.greetingAfternoon, isNotEmpty, reason: 'greetingAfternoon');
      expect(l.greetingEvening, isNotEmpty, reason: 'greetingEvening');
      expect(l.greetingMorning, isNotEmpty, reason: 'greetingMorning');
      expect(l.hapticFeedback, isNotEmpty, reason: 'hapticFeedback');
      expect(l.hapticSubtitle, isNotEmpty, reason: 'hapticSubtitle');
      expect(l.hidePassword, isNotEmpty, reason: 'hidePassword');
      expect(l.homeAllComplete, isNotEmpty, reason: 'homeAllComplete');
      expect(l.homeAllCompleteDesc, isNotEmpty, reason: 'homeAllCompleteDesc');
      expect(l.homeContinue, isNotEmpty, reason: 'homeContinue');
      expect(l.homeDefaultName, isNotEmpty, reason: 'homeDefaultName');
      expect(l.homeLearningPath, isNotEmpty, reason: 'homeLearningPath');
      expect(
        l.homeViewAchievements,
        isNotEmpty,
        reason: 'homeViewAchievements',
      );
      expect(l.incorrect, isNotEmpty, reason: 'incorrect');
      expect(l.incorrectAnswer, isNotEmpty, reason: 'incorrectAnswer');
      expect(l.languageSpanish, isNotEmpty, reason: 'languageSpanish');
      expect(l.languageEnglish, isNotEmpty, reason: 'languageEnglish');
      expect(l.languageFrench, isNotEmpty, reason: 'languageFrench');
      expect(l.languagePortuguese, isNotEmpty, reason: 'languagePortuguese');
      expect(l.lastSync, isNotEmpty, reason: 'lastSync');
      expect(l.legalAnd, isNotEmpty, reason: 'legalAnd');
      expect(l.legalRegisterAgree, isNotEmpty, reason: 'legalRegisterAgree');
      expect(l.legalTerms, isNotEmpty, reason: 'legalTerms');
      expect(l.lessonComplete, isNotEmpty, reason: 'lessonComplete');
      expect(l.lessonPreparing, isNotEmpty, reason: 'lessonPreparing');
      expect(
        l.lessonResultsPreparing,
        isNotEmpty,
        reason: 'lessonResultsPreparing',
      );
      expect(l.reviewCompleted, isNotEmpty, reason: 'reviewCompleted');
      expect(l.reviewGemsLabel, isNotEmpty, reason: 'reviewGemsLabel');
      expect(l.reviewNoneDue, isNotEmpty, reason: 'reviewNoneDue');
      expect(l.reviewScreenTitle, isNotEmpty, reason: 'reviewScreenTitle');
      expect(l.reviewXpLabel, isNotEmpty, reason: 'reviewXpLabel');
      expect(l.lessonsYourPath, isNotEmpty, reason: 'lessonsYourPath');
      expect(l.loading, isNotEmpty, reason: 'loading');
      expect(l.miniGameBackupDef, isNotEmpty, reason: 'miniGameBackupDef');
      expect(l.miniGameBackupTerm, isNotEmpty, reason: 'miniGameBackupTerm');
      expect(l.miniGameComplete, isNotEmpty, reason: 'miniGameComplete');
      expect(l.miniGameCorrect, isNotEmpty, reason: 'miniGameCorrect');
      expect(
        l.miniGameEncryptionDef,
        isNotEmpty,
        reason: 'miniGameEncryptionDef',
      );
      expect(
        l.miniGameEncryptionTerm,
        isNotEmpty,
        reason: 'miniGameEncryptionTerm',
      );
      expect(l.miniGameFirewallDef, isNotEmpty, reason: 'miniGameFirewallDef');
      expect(
        l.miniGameFirewallTerm,
        isNotEmpty,
        reason: 'miniGameFirewallTerm',
      );
      expect(l.miniGameHiddenCard, isNotEmpty, reason: 'miniGameHiddenCard');
      expect(l.miniGameMalwareDef, isNotEmpty, reason: 'miniGameMalwareDef');
      expect(l.miniGameMalwareTerm, isNotEmpty, reason: 'miniGameMalwareTerm');
      expect(l.miniGameMatches, isNotEmpty, reason: 'miniGameMatches');
      expect(l.miniGameMemory, isNotEmpty, reason: 'miniGameMemory');
      expect(l.miniGameMemoryDesc, isNotEmpty, reason: 'miniGameMemoryDesc');
      expect(l.miniGameMistakes, isNotEmpty, reason: 'miniGameMistakes');
      expect(l.miniGameMoves, isNotEmpty, reason: 'miniGameMoves');
      expect(l.miniGameOver, isNotEmpty, reason: 'miniGameOver');
      expect(l.miniGamePattern, isNotEmpty, reason: 'miniGamePattern');
      expect(l.miniGamePatternDesc, isNotEmpty, reason: 'miniGamePatternDesc');
      expect(l.miniGamePhishingDef, isNotEmpty, reason: 'miniGamePhishingDef');
      expect(
        l.miniGamePhishingTerm,
        isNotEmpty,
        reason: 'miniGamePhishingTerm',
      );
      expect(l.miniGamePlayAgain, isNotEmpty, reason: 'miniGamePlayAgain');
      expect(l.miniGameRound, isNotEmpty, reason: 'miniGameRound');
      expect(l.miniGameScore, isNotEmpty, reason: 'miniGameScore');
      expect(
        l.miniGameSortInstruction,
        isNotEmpty,
        reason: 'miniGameSortInstruction',
      );
      expect(l.miniGameSpeed, isNotEmpty, reason: 'miniGameSpeed');
      expect(l.miniGameSpeedDesc, isNotEmpty, reason: 'miniGameSpeedDesc');
      expect(l.miniGameSubtitle, isNotEmpty, reason: 'miniGameSubtitle');
      expect(l.miniGameTitle, isNotEmpty, reason: 'miniGameTitle');
      expect(l.miniGameVpnDef, isNotEmpty, reason: 'miniGameVpnDef');
      expect(l.miniGameVpnTerm, isNotEmpty, reason: 'miniGameVpnTerm');
      expect(l.miniGameWatch, isNotEmpty, reason: 'miniGameWatch');
      expect(l.miniGameWord, isNotEmpty, reason: 'miniGameWord');
      expect(l.miniGameWordDesc, isNotEmpty, reason: 'miniGameWordDesc');
      expect(l.miniGameWrong, isNotEmpty, reason: 'miniGameWrong');
      expect(l.miniGameYourTurn, isNotEmpty, reason: 'miniGameYourTurn');
      expect(
        l.missionActiveLearnerDesc,
        isNotEmpty,
        reason: 'missionActiveLearnerDesc',
      );
      expect(
        l.missionActiveLearnerTitle,
        isNotEmpty,
        reason: 'missionActiveLearnerTitle',
      );
      expect(
        l.missionActiveStreakDesc,
        isNotEmpty,
        reason: 'missionActiveStreakDesc',
      );
      expect(
        l.missionActiveStreakTitle,
        isNotEmpty,
        reason: 'missionActiveStreakTitle',
      );
      expect(
        l.missionChatWithSageDesc,
        isNotEmpty,
        reason: 'missionChatWithSageDesc',
      );
      expect(
        l.missionChatWithSageTitle,
        isNotEmpty,
        reason: 'missionChatWithSageTitle',
      );
      expect(
        l.missionDigitalDetectiveDesc,
        isNotEmpty,
        reason: 'missionDigitalDetectiveDesc',
      );
      expect(
        l.missionDigitalDetectiveTitle,
        isNotEmpty,
        reason: 'missionDigitalDetectiveTitle',
      );
      expect(
        l.missionExpressChallengeDesc,
        isNotEmpty,
        reason: 'missionExpressChallengeDesc',
      );
      expect(
        l.missionExpressChallengeTitle,
        isNotEmpty,
        reason: 'missionExpressChallengeTitle',
      );
      expect(
        l.missionPerfectLessonDesc,
        isNotEmpty,
        reason: 'missionPerfectLessonDesc',
      );
      expect(
        l.missionPerfectLessonTitle,
        isNotEmpty,
        reason: 'missionPerfectLessonTitle',
      );
      expect(
        l.missionPhishingHunterDesc,
        isNotEmpty,
        reason: 'missionPhishingHunterDesc',
      );
      expect(
        l.missionPhishingHunterTitle,
        isNotEmpty,
        reason: 'missionPhishingHunterTitle',
      );
      expect(l.motivationCareer, isNotEmpty, reason: 'motivationCareer');
      expect(l.motivationConnect, isNotEmpty, reason: 'motivationConnect');
      expect(
        l.motivationDialogMultiple,
        isNotEmpty,
        reason: 'motivationDialogMultiple',
      );
      expect(
        l.motivationDialogNone,
        isNotEmpty,
        reason: 'motivationDialogNone',
      );
      expect(l.motivationFun, isNotEmpty, reason: 'motivationFun');
      expect(l.motivationMind, isNotEmpty, reason: 'motivationMind');
      expect(l.motivationOther, isNotEmpty, reason: 'motivationOther');
      expect(l.motivationStudies, isNotEmpty, reason: 'motivationStudies');
      expect(l.motivationTravel, isNotEmpty, reason: 'motivationTravel');
      expect(l.navChest, isNotEmpty, reason: 'navChest');
      expect(l.navHome, isNotEmpty, reason: 'navHome');
      expect(l.navProfile, isNotEmpty, reason: 'navProfile');
      expect(l.navRanking, isNotEmpty, reason: 'navRanking');
      expect(l.navSage, isNotEmpty, reason: 'navSage');
      expect(l.nextText, isNotEmpty, reason: 'nextText');
      expect(l.noLessonsAvailable, isNotEmpty, reason: 'noLessonsAvailable');
      expect(l.notFoundBackHome, isNotEmpty, reason: 'notFoundBackHome');
      expect(l.notFoundDescription, isNotEmpty, reason: 'notFoundDescription');
      expect(l.notFoundTitle, isNotEmpty, reason: 'notFoundTitle');
      expect(
        l.offlineSavedForLater,
        isNotEmpty,
        reason: 'offlineSavedForLater',
      );
      expect(
        l.onbMotivationCareerMsg,
        isNotEmpty,
        reason: 'onbMotivationCareerMsg',
      );
      expect(
        l.onbMotivationConnectMsg,
        isNotEmpty,
        reason: 'onbMotivationConnectMsg',
      );
      expect(l.onbMotivationFunMsg, isNotEmpty, reason: 'onbMotivationFunMsg');
      expect(
        l.onbMotivationMindMsg,
        isNotEmpty,
        reason: 'onbMotivationMindMsg',
      );
      expect(
        l.onbMotivationOtherMsg,
        isNotEmpty,
        reason: 'onbMotivationOtherMsg',
      );
      expect(
        l.onbMotivationStudiesMsg,
        isNotEmpty,
        reason: 'onbMotivationStudiesMsg',
      );
      expect(l.onbMotivationTitle, isNotEmpty, reason: 'onbMotivationTitle');
      expect(
        l.onbMotivationTravelMsg,
        isNotEmpty,
        reason: 'onbMotivationTravelMsg',
      );
      expect(l.onbProjectionTitle, isNotEmpty, reason: 'onbProjectionTitle');
      expect(l.onbRouteAvailable, isNotEmpty, reason: 'onbRouteAvailable');
      expect(l.onbRouteQuestion, isNotEmpty, reason: 'onbRouteQuestion');
      expect(
        l.onbStartingExperienced,
        isNotEmpty,
        reason: 'onbStartingExperienced',
      );
      expect(
        l.onbStartingExperiencedSub,
        isNotEmpty,
        reason: 'onbStartingExperiencedSub',
      );
      expect(l.onbStartingPerfecto, isNotEmpty, reason: 'onbStartingPerfecto');
      expect(l.onbStartingSubtitle, isNotEmpty, reason: 'onbStartingSubtitle');
      expect(l.onbStartingTitle, isNotEmpty, reason: 'onbStartingTitle');
      expect(l.onbWelcomeMsg, isNotEmpty, reason: 'onbWelcomeMsg');
      expect(
        l.onboardingCommitButton,
        isNotEmpty,
        reason: 'onboardingCommitButton',
      );
      expect(l.onboardingDesc, isNotEmpty, reason: 'onboardingDesc');
      expect(
        l.onboardingHaveAccount,
        isNotEmpty,
        reason: 'onboardingHaveAccount',
      );
      expect(
        l.onboardingSage50Days,
        isNotEmpty,
        reason: 'onboardingSage50Days',
      );
      expect(
        l.onboardingSageExcellent,
        isNotEmpty,
        reason: 'onboardingSageExcellent',
      );
      expect(l.onboardingSageMonth, isNotEmpty, reason: 'onboardingSageMonth');
      expect(l.onboardingSageStart, isNotEmpty, reason: 'onboardingSageStart');
      expect(
        l.onboardingSageTwoWeeks,
        isNotEmpty,
        reason: 'onboardingSageTwoWeeks',
      );
      expect(l.owned, isNotEmpty, reason: 'owned');
      expect(l.passClaimFailed, isNotEmpty, reason: 'passClaimFailed');
      expect(l.passClaimedLabel, isNotEmpty, reason: 'passClaimedLabel');
      expect(l.passEarnSp, isNotEmpty, reason: 'passEarnSp');
      expect(
        l.passHowToEarnDailyLimit,
        isNotEmpty,
        reason: 'passHowToEarnDailyLimit',
      );
      expect(l.passHowToEarnLesson, isNotEmpty, reason: 'passHowToEarnLesson');
      expect(
        l.passHowToEarnMission,
        isNotEmpty,
        reason: 'passHowToEarnMission',
      );
      expect(
        l.passHowToEarnPerfect,
        isNotEmpty,
        reason: 'passHowToEarnPerfect',
      );
      expect(l.passHowToEarnReview, isNotEmpty, reason: 'passHowToEarnReview');
      expect(l.passHowToEarnTitle, isNotEmpty, reason: 'passHowToEarnTitle');
      expect(l.passLevelsTitle, isNotEmpty, reason: 'passLevelsTitle');
      expect(l.passLocked, isNotEmpty, reason: 'passLocked');
      expect(l.passMaxLevel, isNotEmpty, reason: 'passMaxLevel');
      expect(l.passReached, isNotEmpty, reason: 'passReached');
      expect(l.passRewardClaimed, isNotEmpty, reason: 'passRewardClaimed');
      expect(l.paymentGoHome, isNotEmpty, reason: 'paymentGoHome');
      expect(
        l.paymentMercadoPagoError,
        isNotEmpty,
        reason: 'paymentMercadoPagoError',
      );
      expect(l.paymentNotCompleted, isNotEmpty, reason: 'paymentNotCompleted');
      expect(l.paymentPending, isNotEmpty, reason: 'paymentPending');
      expect(
        l.paymentPendingDescription,
        isNotEmpty,
        reason: 'paymentPendingDescription',
      );
      expect(l.paymentTryAgain, isNotEmpty, reason: 'paymentTryAgain');
      expect(
        l.paymentErrorNotSignedIn,
        isNotEmpty,
        reason: 'paymentErrorNotSignedIn',
      );
      expect(
        l.paymentErrorSessionExpired,
        isNotEmpty,
        reason: 'paymentErrorSessionExpired',
      );
      expect(
        l.paymentErrorInvalidProduct,
        isNotEmpty,
        reason: 'paymentErrorInvalidProduct',
      );
      expect(
        l.paymentErrorStartFailed,
        isNotEmpty,
        reason: 'paymentErrorStartFailed',
      );
      expect(
        l.paymentErrorRegisterFailed,
        isNotEmpty,
        reason: 'paymentErrorRegisterFailed',
      );
      expect(l.paymentErrorExpired, isNotEmpty, reason: 'paymentErrorExpired');
      expect(
        l.paymentErrorCancelled,
        isNotEmpty,
        reason: 'paymentErrorCancelled',
      );
      expect(l.paywallBasic, isNotEmpty, reason: 'paywallBasic');
      expect(l.paywallDescription, isNotEmpty, reason: 'paywallDescription');
      expect(l.paywallMercadoPago, isNotEmpty, reason: 'paywallMercadoPago');
      expect(
        l.paywallPaymentMethods,
        isNotEmpty,
        reason: 'paywallPaymentMethods',
      );
      expect(l.paywallPopular, isNotEmpty, reason: 'paywallPopular');
      expect(l.paywallPremium, isNotEmpty, reason: 'paywallPremium');
      expect(l.paywallSupportUs, isNotEmpty, reason: 'paywallSupportUs');
      expect(l.privacyPolicy, isNotEmpty, reason: 'privacyPolicy');
      expect(l.privacyPolicyTitle, isNotEmpty, reason: 'privacyPolicyTitle');
      expect(
        l.privacyPolicyLastUpdate,
        isNotEmpty,
        reason: 'privacyPolicyLastUpdate',
      );
      expect(
        l.privacyPolicySection1Title,
        isNotEmpty,
        reason: 'privacyPolicySection1Title',
      );
      expect(
        l.privacyPolicySection1Body,
        isNotEmpty,
        reason: 'privacyPolicySection1Body',
      );
      expect(
        l.privacyPolicySection2Title,
        isNotEmpty,
        reason: 'privacyPolicySection2Title',
      );
      expect(
        l.privacyPolicySection2Body,
        isNotEmpty,
        reason: 'privacyPolicySection2Body',
      );
      expect(
        l.privacyPolicySection3Title,
        isNotEmpty,
        reason: 'privacyPolicySection3Title',
      );
      expect(
        l.privacyPolicySection3Body,
        isNotEmpty,
        reason: 'privacyPolicySection3Body',
      );
      expect(
        l.privacyPolicySection4Title,
        isNotEmpty,
        reason: 'privacyPolicySection4Title',
      );
      expect(
        l.privacyPolicySection4Body,
        isNotEmpty,
        reason: 'privacyPolicySection4Body',
      );
      expect(
        l.privacyPolicySection5Title,
        isNotEmpty,
        reason: 'privacyPolicySection5Title',
      );
      expect(
        l.privacyPolicySection5Body,
        isNotEmpty,
        reason: 'privacyPolicySection5Body',
      );
      expect(
        l.privacyPolicySection6Title,
        isNotEmpty,
        reason: 'privacyPolicySection6Title',
      );
      expect(
        l.privacyPolicySection6Body,
        isNotEmpty,
        reason: 'privacyPolicySection6Body',
      );
      expect(
        l.privacyPolicySection7Title,
        isNotEmpty,
        reason: 'privacyPolicySection7Title',
      );
      expect(
        l.privacyPolicySection7Body,
        isNotEmpty,
        reason: 'privacyPolicySection7Body',
      );
      expect(
        l.privacyPolicySection8Title,
        isNotEmpty,
        reason: 'privacyPolicySection8Title',
      );
      expect(
        l.privacyPolicySection8Body,
        isNotEmpty,
        reason: 'privacyPolicySection8Body',
      );
      expect(
        l.privacyPolicySection9Title,
        isNotEmpty,
        reason: 'privacyPolicySection9Title',
      );
      expect(
        l.privacyPolicySection9Body,
        isNotEmpty,
        reason: 'privacyPolicySection9Body',
      );
      expect(l.productBestOffer, isNotEmpty, reason: 'productBestOffer');
      expect(l.productBoost, isNotEmpty, reason: 'productBoost');
      expect(l.productBoostPack, isNotEmpty, reason: 'productBoostPack');
      expect(
        l.productBoostPackDesc,
        isNotEmpty,
        reason: 'productBoostPackDesc',
      );
      expect(
        l.productDonationBasic,
        isNotEmpty,
        reason: 'productDonationBasic',
      );
      expect(l.productDonationDesc, isNotEmpty, reason: 'productDonationDesc');
      expect(
        l.productDonationPremium,
        isNotEmpty,
        reason: 'productDonationPremium',
      );
      expect(
        l.productDonationStandard,
        isNotEmpty,
        reason: 'productDonationStandard',
      );
      expect(l.productLuck, isNotEmpty, reason: 'productLuck');
      expect(
        l.productLuckBoostDesc,
        isNotEmpty,
        reason: 'productLuckBoostDesc',
      );
      expect(l.productLuckPack, isNotEmpty, reason: 'productLuckPack');
      expect(l.productLuckPackDesc, isNotEmpty, reason: 'productLuckPackDesc');
      expect(l.productPopular, isNotEmpty, reason: 'productPopular');
      expect(l.productProtector, isNotEmpty, reason: 'productProtector');
      expect(
        l.productProtectorPack,
        isNotEmpty,
        reason: 'productProtectorPack',
      );
      expect(
        l.productProtectorPackDesc,
        isNotEmpty,
        reason: 'productProtectorPackDesc',
      );
      expect(
        l.productStreakProtectorDesc,
        isNotEmpty,
        reason: 'productStreakProtectorDesc',
      );
      expect(l.productSupporter, isNotEmpty, reason: 'productSupporter');
      expect(l.productXpBoostDesc, isNotEmpty, reason: 'productXpBoostDesc');
      expect(l.profileAchievements, isNotEmpty, reason: 'profileAchievements');
      expect(l.profileDay, isNotEmpty, reason: 'profileDay');
      expect(l.profileDays, isNotEmpty, reason: 'profileDays');
      expect(
        l.profileDefaultFirstName,
        isNotEmpty,
        reason: 'profileDefaultFirstName',
      );
      expect(
        l.profileDefaultLastName,
        isNotEmpty,
        reason: 'profileDefaultLastName',
      );
      expect(l.profileDefaultName, isNotEmpty, reason: 'profileDefaultName');
      expect(l.profileDonations, isNotEmpty, reason: 'profileDonations');
      expect(l.profileError, isNotEmpty, reason: 'profileError');
      expect(l.profileLevel, isNotEmpty, reason: 'profileLevel');
      expect(l.profileStreak, isNotEmpty, reason: 'profileStreak');
      expect(l.profileGemsEarned, isNotEmpty, reason: 'profileGemsEarned');
      expect(l.profileGemsSpent, isNotEmpty, reason: 'profileGemsSpent');
      expect(l.profileTotalXp, isNotEmpty, reason: 'profileTotalXp');
      expect(l.profileXpLabel, isNotEmpty, reason: 'profileXpLabel');
      expect(
        l.projectionBenefit1Subtitle,
        isNotEmpty,
        reason: 'projectionBenefit1Subtitle',
      );
      expect(
        l.projectionBenefit1Title,
        isNotEmpty,
        reason: 'projectionBenefit1Title',
      );
      expect(
        l.projectionBenefit2Subtitle,
        isNotEmpty,
        reason: 'projectionBenefit2Subtitle',
      );
      expect(
        l.projectionBenefit2Title,
        isNotEmpty,
        reason: 'projectionBenefit2Title',
      );
      expect(
        l.projectionBenefit3Subtitle,
        isNotEmpty,
        reason: 'projectionBenefit3Subtitle',
      );
      expect(
        l.projectionBenefit3Title,
        isNotEmpty,
        reason: 'projectionBenefit3Title',
      );
      expect(l.protectionBasic, isNotEmpty, reason: 'protectionBasic');
      expect(l.protectionBasicDesc, isNotEmpty, reason: 'protectionBasicDesc');
      expect(
        l.protectionCyberShield,
        isNotEmpty,
        reason: 'protectionCyberShield',
      );
      expect(
        l.protectionCyberShieldDesc,
        isNotEmpty,
        reason: 'protectionCyberShieldDesc',
      );
      expect(l.protectionElite, isNotEmpty, reason: 'protectionElite');
      expect(l.protectionEliteDesc, isNotEmpty, reason: 'protectionEliteDesc');
      expect(l.protectionGuardian, isNotEmpty, reason: 'protectionGuardian');
      expect(
        l.protectionGuardianDesc,
        isNotEmpty,
        reason: 'protectionGuardianDesc',
      );
      expect(l.protectionProtected, isNotEmpty, reason: 'protectionProtected');
      expect(
        l.protectionProtectedDesc,
        isNotEmpty,
        reason: 'protectionProtectedDesc',
      );
      expect(
        l.protectionSecureMind,
        isNotEmpty,
        reason: 'protectionSecureMind',
      );
      expect(
        l.protectionSecureMindDesc,
        isNotEmpty,
        reason: 'protectionSecureMindDesc',
      );
      expect(
        l.quickChallengeDetectPhishing,
        isNotEmpty,
        reason: 'quickChallengeDetectPhishing',
      );
      expect(
        l.quickChallengeDetectRisk,
        isNotEmpty,
        reason: 'quickChallengeDetectRisk',
      );
      expect(
        l.quickChallengeSafePassword,
        isNotEmpty,
        reason: 'quickChallengeSafePassword',
      );
      expect(
        l.quickChallengeTrueFalse,
        isNotEmpty,
        reason: 'quickChallengeTrueFalse',
      );
      expect(
        l.quickChallengeWhatWouldYouDo,
        isNotEmpty,
        reason: 'quickChallengeWhatWouldYouDo',
      );
      expect(l.rankActiveLearner, isNotEmpty, reason: 'rankActiveLearner');
      expect(
        l.rankCybersecurityLegend,
        isNotEmpty,
        reason: 'rankCybersecurityLegend',
      );
      expect(l.rankEliteDefender, isNotEmpty, reason: 'rankEliteDefender');
      expect(
        l.rankExperiencedWarrior,
        isNotEmpty,
        reason: 'rankExperiencedWarrior',
      );
      expect(l.rankNovice, isNotEmpty, reason: 'rankNovice');
      expect(l.rankingEmptyMessage, isNotEmpty, reason: 'rankingEmptyMessage');
      expect(l.rankingError, isNotEmpty, reason: 'rankingError');
      expect(l.rankingShareButton, isNotEmpty, reason: 'rankingShareButton');
      expect(
        l.rankingShareSubtitle,
        isNotEmpty,
        reason: 'rankingShareSubtitle',
      );
      expect(l.rankingSharing, isNotEmpty, reason: 'rankingSharing');
      expect(l.rankingSubtitle, isNotEmpty, reason: 'rankingSubtitle');
      expect(l.rankingTitle, isNotEmpty, reason: 'rankingTitle');
      expect(l.rankingPodiumLabel, isNotEmpty, reason: 'rankingPodiumLabel');
      expect(l.rarityGold, isNotEmpty, reason: 'rarityGold');
      expect(l.rarityPlatinum, isNotEmpty, reason: 'rarityPlatinum');
      expect(l.raritySilver, isNotEmpty, reason: 'raritySilver');
      expect(l.recommended, isNotEmpty, reason: 'recommended');
      expect(l.reduceAnimations, isNotEmpty, reason: 'reduceAnimations');
      expect(
        l.reduceAnimationsSubtitle,
        isNotEmpty,
        reason: 'reduceAnimationsSubtitle',
      );
      expect(l.regAgeQuestion, isNotEmpty, reason: 'regAgeQuestion');
      expect(l.regAgeValidation, isNotEmpty, reason: 'regAgeValidation');
      expect(l.regChooseMethod, isNotEmpty, reason: 'regChooseMethod');
      expect(l.regCloudSave, isNotEmpty, reason: 'regCloudSave');
      expect(l.regCreateProfile, isNotEmpty, reason: 'regCreateProfile');
      expect(l.regEmailDesc, isNotEmpty, reason: 'regEmailDesc');
      expect(l.regEmailHint, isNotEmpty, reason: 'regEmailHint');
      expect(l.regEmailOption, isNotEmpty, reason: 'regEmailOption');
      expect(l.regEmailTitle, isNotEmpty, reason: 'regEmailTitle');
      expect(l.regHowContinue, isNotEmpty, reason: 'regHowContinue');
      expect(l.regLater, isNotEmpty, reason: 'regLater');
      expect(l.regNameHint, isNotEmpty, reason: 'regNameHint');
      expect(l.regNameQuestion, isNotEmpty, reason: 'regNameQuestion');
      expect(l.regPasswordDesc, isNotEmpty, reason: 'regPasswordDesc');
      expect(l.regPasswordTitle, isNotEmpty, reason: 'regPasswordTitle');
      expect(
        l.regProfileAlmostReady,
        isNotEmpty,
        reason: 'regProfileAlmostReady',
      );
      expect(l.regProfileCreated, isNotEmpty, reason: 'regProfileCreated');
      expect(l.regProfileDesc, isNotEmpty, reason: 'regProfileDesc');
      expect(l.regReadyForLesson, isNotEmpty, reason: 'regReadyForLesson');
      expect(l.regRewards, isNotEmpty, reason: 'regRewards');
      expect(l.regStreakSync, isNotEmpty, reason: 'regStreakSync');
      expect(l.regSurnameHint, isNotEmpty, reason: 'regSurnameHint');
      expect(l.regWelcomeSagen, isNotEmpty, reason: 'regWelcomeSagen');
      expect(l.resultAccuracy, isNotEmpty, reason: 'resultAccuracy');
      expect(l.resultCompleteTitle, isNotEmpty, reason: 'resultCompleteTitle');
      expect(l.resultLives, isNotEmpty, reason: 'resultLives');
      expect(
        l.resultNotPerfectDesc,
        isNotEmpty,
        reason: 'resultNotPerfectDesc',
      );
      expect(l.resultPerfectBadge, isNotEmpty, reason: 'resultPerfectBadge');
      expect(l.resultPerfectDesc, isNotEmpty, reason: 'resultPerfectDesc');
      expect(l.resultPerfectTitle, isNotEmpty, reason: 'resultPerfectTitle');
      expect(l.resumeQuiz, isNotEmpty, reason: 'resumeQuiz');
      expect(l.resumeLessonBody, isNotEmpty, reason: 'resumeLessonBody');
      expect(l.resumeContinue, isNotEmpty, reason: 'resumeContinue');
      expect(l.retryStart, isNotEmpty, reason: 'retryStart');
      expect(l.retry, isNotEmpty, reason: 'retry');
      expect(l.reward100Xp, isNotEmpty, reason: 'reward100Xp');
      expect(l.reward200Exp, isNotEmpty, reason: 'reward200Exp');
      expect(l.rewardCopperFrame, isNotEmpty, reason: 'rewardCopperFrame');
      expect(l.rewardEpicChest, isNotEmpty, reason: 'rewardEpicChest');
      expect(l.rewardGoldenChest, isNotEmpty, reason: 'rewardGoldenChest');
      expect(l.rewardIceFlame, isNotEmpty, reason: 'rewardIceFlame');
      expect(
        l.rewardTitaniumShield,
        isNotEmpty,
        reason: 'rewardTitaniumShield',
      );
      expect(l.routeSelection1, isNotEmpty, reason: 'routeSelection1');
      expect(l.routeSelection2, isNotEmpty, reason: 'routeSelection2');
      expect(l.routeSelection3, isNotEmpty, reason: 'routeSelection3');
      expect(l.sageMonocleActive, isNotEmpty, reason: 'sageMonocleActive');
      expect(l.sageMonocleButton, isNotEmpty, reason: 'sageMonocleButton');
      expect(
        l.sagenPassSupportSubtitle,
        isNotEmpty,
        reason: 'sagenPassSupportSubtitle',
      );
      expect(
        l.sagenPassSupportTitle,
        isNotEmpty,
        reason: 'sagenPassSupportTitle',
      );
      expect(l.sagenPassTitle, isNotEmpty, reason: 'sagenPassTitle');
      expect(l.selectedAnswer, isNotEmpty, reason: 'selectedAnswer');
      expect(l.sendMessage, isNotEmpty, reason: 'sendMessage');
      expect(l.sessionBackToMap, isNotEmpty, reason: 'sessionBackToMap');
      expect(l.sessionCorrect, isNotEmpty, reason: 'sessionCorrect');
      expect(l.sessionIncorrect, isNotEmpty, reason: 'sessionIncorrect');
      expect(
        l.sessionLivesExhausted,
        isNotEmpty,
        reason: 'sessionLivesExhausted',
      );
      expect(
        l.sessionLivesExhaustedDesc,
        isNotEmpty,
        reason: 'sessionLivesExhaustedDesc',
      );
      expect(l.sessionLoading, isNotEmpty, reason: 'sessionLoading');
      expect(l.sessionRetry, isNotEmpty, reason: 'sessionRetry');
      expect(l.sessionSelectAnswer, isNotEmpty, reason: 'sessionSelectAnswer');
      expect(l.settingsLanguage, isNotEmpty, reason: 'settingsLanguage');
      expect(l.settingsLogout, isNotEmpty, reason: 'settingsLogout');
      expect(
        l.settingsLogoutConfirm,
        isNotEmpty,
        reason: 'settingsLogoutConfirm',
      );
      expect(
        l.settingsNotifications,
        isNotEmpty,
        reason: 'settingsNotifications',
      );
      expect(
        l.settingsNotificationsSubtitle,
        isNotEmpty,
        reason: 'settingsNotificationsSubtitle',
      );
      expect(l.settingsTitle, isNotEmpty, reason: 'settingsTitle');
      expect(l.shareProfile, isNotEmpty, reason: 'shareProfile');
      expect(l.shareRanking, isNotEmpty, reason: 'shareRanking');
      expect(l.sharing, isNotEmpty, reason: 'sharing');
      expect(l.showPassword, isNotEmpty, reason: 'showPassword');
      expect(l.skipText, isNotEmpty, reason: 'skipText');
      expect(l.skipToContent, isNotEmpty, reason: 'skipToContent');
      expect(l.sounds, isNotEmpty, reason: 'sounds');
      expect(l.soundsSubtitle, isNotEmpty, reason: 'soundsSubtitle');
      expect(l.speedSort2fa, isNotEmpty, reason: 'speedSort2fa');
      expect(l.speedSortAntivirus, isNotEmpty, reason: 'speedSortAntivirus');
      expect(
        l.speedSortDataEncryption,
        isNotEmpty,
        reason: 'speedSortDataEncryption',
      );
      expect(l.speedSortFakeEmail, isNotEmpty, reason: 'speedSortFakeEmail');
      expect(l.speedSortFirewall, isNotEmpty, reason: 'speedSortFirewall');
      expect(
        l.speedSortFraudulentCall,
        isNotEmpty,
        reason: 'speedSortFraudulentCall',
      );
      expect(
        l.speedSortProtectionCategory,
        isNotEmpty,
        reason: 'speedSortProtectionCategory',
      );
      expect(
        l.speedSortScamCategory,
        isNotEmpty,
        reason: 'speedSortScamCategory',
      );
      expect(
        l.speedSortSecurityCategory,
        isNotEmpty,
        reason: 'speedSortSecurityCategory',
      );
      expect(l.speedSortSmsLink, isNotEmpty, reason: 'speedSortSmsLink');
      expect(
        l.speedSortStrongPassword,
        isNotEmpty,
        reason: 'speedSortStrongPassword',
      );
      expect(l.speedSortVpn, isNotEmpty, reason: 'speedSortVpn');
      expect(l.splashTitle, isNotEmpty, reason: 'splashTitle');
      expect(l.startText, isNotEmpty, reason: 'startText');
      expect(l.statsExcellent, isNotEmpty, reason: 'statsExcellent');
      expect(l.statsIncredible, isNotEmpty, reason: 'statsIncredible');
      expect(l.statsKeepTrying, isNotEmpty, reason: 'statsKeepTrying');
      expect(l.statsNoData, isNotEmpty, reason: 'statsNoData');
      expect(l.statsNoErrors, isNotEmpty, reason: 'statsNoErrors');
      expect(l.statsReceiveXp, isNotEmpty, reason: 'statsReceiveXp');
      expect(l.statsSpeed, isNotEmpty, reason: 'statsSpeed');
      expect(l.statsStartStage1, isNotEmpty, reason: 'statsStartStage1');
      expect(l.statsStartStage2, isNotEmpty, reason: 'statsStartStage2');
      expect(l.statsWellDone, isNotEmpty, reason: 'statsWellDone');
      expect(l.statusCompleted, isNotEmpty, reason: 'statusCompleted');
      expect(
        l.storeCategoryConsumables,
        isNotEmpty,
        reason: 'storeCategoryConsumables',
      );
      expect(
        l.storeCategoryCosmetics,
        isNotEmpty,
        reason: 'storeCategoryCosmetics',
      );
      expect(l.storeCategoryThemes, isNotEmpty, reason: 'storeCategoryThemes');
      expect(l.storeConfirmTitle, isNotEmpty, reason: 'storeConfirmTitle');
      expect(
        l.storeGemTipAchievement,
        isNotEmpty,
        reason: 'storeGemTipAchievement',
      );
      expect(l.storeGemTipChest, isNotEmpty, reason: 'storeGemTipChest');
      expect(
        l.storeGemTipFirstLesson,
        isNotEmpty,
        reason: 'storeGemTipFirstLesson',
      );
      expect(l.storeGemTipLesson, isNotEmpty, reason: 'storeGemTipLesson');
      expect(l.storeGemTipMission, isNotEmpty, reason: 'storeGemTipMission');
      expect(l.storeGemTipPerfect, isNotEmpty, reason: 'storeGemTipPerfect');
      expect(l.storeGemTipStreak, isNotEmpty, reason: 'storeGemTipStreak');
      expect(l.storeHowToEarnGems, isNotEmpty, reason: 'storeHowToEarnGems');
      expect(
        l.storePersonalization,
        isNotEmpty,
        reason: 'storePersonalization',
      );
      expect(l.storeProtectStreak, isNotEmpty, reason: 'storeProtectStreak');
      expect(
        l.storeDailyChestClaim,
        isNotEmpty,
        reason: 'storeDailyChestClaim',
      );
      expect(
        l.storeDailyChestSubtitle,
        isNotEmpty,
        reason: 'storeDailyChestSubtitle',
      );
      expect(
        l.storeDailyChestTitle,
        isNotEmpty,
        reason: 'storeDailyChestTitle',
      );
      expect(l.storePurchaseFailed, isNotEmpty, reason: 'storePurchaseFailed');
      expect(
        l.storePurchaseSuccess,
        isNotEmpty,
        reason: 'storePurchaseSuccess',
      );
      expect(l.storeAlreadyOwned, isNotEmpty, reason: 'storeAlreadyOwned');
      expect(
        l.storeShieldLimitReached,
        isNotEmpty,
        reason: 'storeShieldLimitReached',
      );
      expect(l.storeSupportTiers, isNotEmpty, reason: 'storeSupportTiers');
      expect(l.storeTitle, isNotEmpty, reason: 'storeTitle');
      expect(l.streakAchievements, isNotEmpty, reason: 'streakAchievements');
      expect(l.streakBadge, isNotEmpty, reason: 'streakBadge');
      expect(l.streakDayLabel, isNotEmpty, reason: 'streakDayLabel');
      expect(l.streakFireCardLabel, isNotEmpty, reason: 'streakFireCardLabel');
      expect(l.streakFreeze, isNotEmpty, reason: 'streakFreeze');
      expect(
        l.streakFreezeDescription,
        isNotEmpty,
        reason: 'streakFreezeDescription',
      );
      expect(l.streakFrozen, isNotEmpty, reason: 'streakFrozen');
      expect(l.streakGotIt, isNotEmpty, reason: 'streakGotIt');
      expect(l.streakKeepAlive, isNotEmpty, reason: 'streakKeepAlive');
      expect(l.streakKeepAliveDesc, isNotEmpty, reason: 'streakKeepAliveDesc');
      expect(l.streakMsg1, isNotEmpty, reason: 'streakMsg1');
      expect(l.streakMsg2, isNotEmpty, reason: 'streakMsg2');
      expect(l.streakMsg3, isNotEmpty, reason: 'streakMsg3');
      expect(l.streakMsg4, isNotEmpty, reason: 'streakMsg4');
      expect(l.streakMsg5, isNotEmpty, reason: 'streakMsg5');
      expect(
        l.streakNoActiveStreak,
        isNotEmpty,
        reason: 'streakNoActiveStreak',
      );
      expect(l.streakRewards, isNotEmpty, reason: 'streakRewards');
      expect(l.streakShieldActive, isNotEmpty, reason: 'streakShieldActive');
      expect(
        l.streakShieldOnboarding,
        isNotEmpty,
        reason: 'streakShieldOnboarding',
      );
      expect(
        l.streakStrongerShield,
        isNotEmpty,
        reason: 'streakStrongerShield',
      );
      expect(l.summaryCommitment, isNotEmpty, reason: 'summaryCommitment');
      expect(l.summaryDailyGoal, isNotEmpty, reason: 'summaryDailyGoal');
      expect(l.summaryKnowledge, isNotEmpty, reason: 'summaryKnowledge');
      expect(l.summaryLearning, isNotEmpty, reason: 'summaryLearning');
      expect(l.summaryPreferences, isNotEmpty, reason: 'summaryPreferences');
      expect(l.summaryMotivations, isNotEmpty, reason: 'summaryMotivations');
      expect(l.summaryOrigin, isNotEmpty, reason: 'summaryOrigin');
      expect(l.summaryReady, isNotEmpty, reason: 'summaryReady');
      expect(l.thankYouForSupport, isNotEmpty, reason: 'thankYouForSupport');
      expect(l.themeDarkLabel, isNotEmpty, reason: 'themeDarkLabel');
      expect(l.themeLabel, isNotEmpty, reason: 'themeLabel');
      expect(l.themeLightLabel, isNotEmpty, reason: 'themeLightLabel');
      expect(l.themeSystemLabel, isNotEmpty, reason: 'themeSystemLabel');
      expect(l.tryAgain, isNotEmpty, reason: 'tryAgain');
      expect(l.tutorLocked, isNotEmpty, reason: 'tutorLocked');
      expect(
        l.tutorLockedDescription,
        isNotEmpty,
        reason: 'tutorLockedDescription',
      );
      expect(
        l.tutorMotivationGeneral,
        isNotEmpty,
        reason: 'tutorMotivationGeneral',
      );
      expect(l.tutorSampleAnswer1, isNotEmpty, reason: 'tutorSampleAnswer1');
      expect(
        l.tutorSampleQuestion1,
        isNotEmpty,
        reason: 'tutorSampleQuestion1',
      );
      expect(
        l.tutorSampleQuestion2,
        isNotEmpty,
        reason: 'tutorSampleQuestion2',
      );
      expect(l.tutorSampleTitle, isNotEmpty, reason: 'tutorSampleTitle');
      expect(l.unknownLabel, isNotEmpty, reason: 'unknownLabel');
      expect(l.updateChangelog, isNotEmpty, reason: 'updateChangelog');
      expect(l.updateChangelogDesc, isNotEmpty, reason: 'updateChangelogDesc');
      expect(l.updateChestSystem, isNotEmpty, reason: 'updateChestSystem');
      expect(
        l.updateChestSystemDesc,
        isNotEmpty,
        reason: 'updateChestSystemDesc',
      );
      expect(l.updateDailyMissions, isNotEmpty, reason: 'updateDailyMissions');
      expect(
        l.updateDailyMissionsDesc,
        isNotEmpty,
        reason: 'updateDailyMissionsDesc',
      );
      expect(l.updateEnergySystem, isNotEmpty, reason: 'updateEnergySystem');
      expect(
        l.updateEnergySystemDesc,
        isNotEmpty,
        reason: 'updateEnergySystemDesc',
      );
      expect(l.updateFirstVersion, isNotEmpty, reason: 'updateFirstVersion');
      expect(
        l.updateFirstVersionDesc,
        isNotEmpty,
        reason: 'updateFirstVersionDesc',
      );
      expect(l.updateImprovedIcons, isNotEmpty, reason: 'updateImprovedIcons');
      expect(
        l.updateImprovedIconsDesc,
        isNotEmpty,
        reason: 'updateImprovedIconsDesc',
      );
      expect(
        l.updateInfiniteEnergy,
        isNotEmpty,
        reason: 'updateInfiniteEnergy',
      );
      expect(
        l.updateInfiniteEnergyDesc,
        isNotEmpty,
        reason: 'updateInfiniteEnergyDesc',
      );
      expect(
        l.updateLessonBoosters,
        isNotEmpty,
        reason: 'updateLessonBoosters',
      );
      expect(
        l.updateLessonBoostersDesc,
        isNotEmpty,
        reason: 'updateLessonBoostersDesc',
      );
      expect(l.updateMercadoPago, isNotEmpty, reason: 'updateMercadoPago');
      expect(
        l.updateMercadoPagoDesc,
        isNotEmpty,
        reason: 'updateMercadoPagoDesc',
      );
      expect(
        l.updateProgrammaticMascot,
        isNotEmpty,
        reason: 'updateProgrammaticMascot',
      );
      expect(
        l.updateProgrammaticMascotDesc,
        isNotEmpty,
        reason: 'updateProgrammaticMascotDesc',
      );
      expect(
        l.updateStreakProtectorImproved,
        isNotEmpty,
        reason: 'updateStreakProtectorImproved',
      );
      expect(
        l.updateStreakProtectorImprovedDesc,
        isNotEmpty,
        reason: 'updateStreakProtectorImprovedDesc',
      );
      expect(l.updateTestFix, isNotEmpty, reason: 'updateTestFix');
      expect(l.updateTestFixDesc, isNotEmpty, reason: 'updateTestFixDesc');
      expect(l.updateTypedRoutes, isNotEmpty, reason: 'updateTypedRoutes');
      expect(
        l.updateTypedRoutesDesc,
        isNotEmpty,
        reason: 'updateTypedRoutesDesc',
      );
      expect(
        l.verifyEmailCheckButton,
        isNotEmpty,
        reason: 'verifyEmailCheckButton',
      );
      expect(
        l.verifyEmailNotVerified,
        isNotEmpty,
        reason: 'verifyEmailNotVerified',
      );
      expect(
        l.verifyEmailResendButton,
        isNotEmpty,
        reason: 'verifyEmailResendButton',
      );
      expect(
        l.verifyEmailResendError,
        isNotEmpty,
        reason: 'verifyEmailResendError',
      );
      expect(l.verifyEmailSent, isNotEmpty, reason: 'verifyEmailSent');
      expect(l.verifyEmailSignOut, isNotEmpty, reason: 'verifyEmailSignOut');
      expect(l.verifyEmailSuccess, isNotEmpty, reason: 'verifyEmailSuccess');
      expect(l.verifyEmailTitle, isNotEmpty, reason: 'verifyEmailTitle');
      expect(l.viewAchievements, isNotEmpty, reason: 'viewAchievements');
      expect(l.welcomeLoginButton, isNotEmpty, reason: 'welcomeLoginButton');
      expect(l.welcomeStartButton, isNotEmpty, reason: 'welcomeStartButton');
      expect(l.welcomeSubtitle, isNotEmpty, reason: 'welcomeSubtitle');
      expect(l.wizardAllAbove, isNotEmpty, reason: 'wizardAllAbove');
      expect(l.wizardAppStore, isNotEmpty, reason: 'wizardAppStore');
      expect(l.wizardArticles, isNotEmpty, reason: 'wizardArticles');
      expect(l.wizardBoostStudies, isNotEmpty, reason: 'wizardBoostStudies');
      expect(l.wizardChatSage, isNotEmpty, reason: 'wizardChatSage');
      expect(l.wizardCommit14, isNotEmpty, reason: 'wizardCommit14');
      expect(l.wizardCommit14Sub, isNotEmpty, reason: 'wizardCommit14Sub');
      expect(l.wizardCommit30, isNotEmpty, reason: 'wizardCommit30');
      expect(l.wizardCommit30Sub, isNotEmpty, reason: 'wizardCommit30Sub');
      expect(l.wizardCommit50, isNotEmpty, reason: 'wizardCommit50');
      expect(l.wizardCommit50Sub, isNotEmpty, reason: 'wizardCommit50Sub');
      expect(l.wizardCommit7, isNotEmpty, reason: 'wizardCommit7');
      expect(l.wizardCommit7Sub, isNotEmpty, reason: 'wizardCommit7Sub');
      expect(l.wizardCommitment, isNotEmpty, reason: 'wizardCommitment');
      expect(
        l.wizardCommitmentSage,
        isNotEmpty,
        reason: 'wizardCommitmentSage',
      );
      expect(l.wizardConfirmed, isNotEmpty, reason: 'wizardConfirmed');
      expect(l.wizardConfirmedSage, isNotEmpty, reason: 'wizardConfirmedSage');
      expect(l.wizardCuriosity, isNotEmpty, reason: 'wizardCuriosity');
      expect(l.wizardDetectScams, isNotEmpty, reason: 'wizardDetectScams');
      expect(l.wizardFacebook, isNotEmpty, reason: 'wizardFacebook');
      expect(l.wizardFriends, isNotEmpty, reason: 'wizardFriends');
      expect(l.wizardGoal10, isNotEmpty, reason: 'wizardGoal10');
      expect(l.wizardGoal10Sub, isNotEmpty, reason: 'wizardGoal10Sub');
      expect(l.wizardGoal15, isNotEmpty, reason: 'wizardGoal15');
      expect(l.wizardGoal15Sub, isNotEmpty, reason: 'wizardGoal15Sub');
      expect(l.wizardGoal3, isNotEmpty, reason: 'wizardGoal3');
      expect(l.wizardGoal30, isNotEmpty, reason: 'wizardGoal30');
      expect(l.wizardGoal30Sub, isNotEmpty, reason: 'wizardGoal30Sub');
      expect(l.wizardGoal3Sub, isNotEmpty, reason: 'wizardGoal3Sub');
      expect(l.wizardGoogle, isNotEmpty, reason: 'wizardGoogle');
      expect(l.wizardHaveFun, isNotEmpty, reason: 'wizardHaveFun');
      expect(l.wizardHowFound, isNotEmpty, reason: 'wizardHowFound');
      expect(l.wizardHowFoundSage, isNotEmpty, reason: 'wizardHowFoundSage');
      expect(l.wizardHowMuchKnow, isNotEmpty, reason: 'wizardHowMuchKnow');
      expect(
        l.wizardHowMuchKnowSage,
        isNotEmpty,
        reason: 'wizardHowMuchKnowSage',
      );
      expect(l.wizardHowPrefer, isNotEmpty, reason: 'wizardHowPrefer');
      expect(l.wizardHowPreferSage, isNotEmpty, reason: 'wizardHowPreferSage');
      expect(l.wizardInstagram, isNotEmpty, reason: 'wizardInstagram');
      expect(l.wizardLevel1, isNotEmpty, reason: 'wizardLevel1');
      expect(l.wizardLevel1Sub, isNotEmpty, reason: 'wizardLevel1Sub');
      expect(l.wizardLevel2, isNotEmpty, reason: 'wizardLevel2');
      expect(l.wizardLevel2Sub, isNotEmpty, reason: 'wizardLevel2Sub');
      expect(l.wizardLevel3, isNotEmpty, reason: 'wizardLevel3');
      expect(l.wizardLevel3Sub, isNotEmpty, reason: 'wizardLevel3Sub');
      expect(l.wizardLevel4, isNotEmpty, reason: 'wizardLevel4');
      expect(l.wizardLevel4Sub, isNotEmpty, reason: 'wizardLevel4Sub');
      expect(l.wizardLevel5, isNotEmpty, reason: 'wizardLevel5');
      expect(l.wizardLevel5Sub, isNotEmpty, reason: 'wizardLevel5Sub');
      expect(l.wizardLinks, isNotEmpty, reason: 'wizardLinks');
      expect(l.wizardNews, isNotEmpty, reason: 'wizardNews');
      expect(l.wizardOther, isNotEmpty, reason: 'wizardOther');
      expect(l.wizardPrepareWork, isNotEmpty, reason: 'wizardPrepareWork');
      expect(l.wizardProtect, isNotEmpty, reason: 'wizardProtect');
      expect(
        l.wizardProtectAccounts,
        isNotEmpty,
        reason: 'wizardProtectAccounts',
      );
      expect(l.wizardProtectFamily, isNotEmpty, reason: 'wizardProtectFamily');
      expect(
        l.wizardProtectPrivacy,
        isNotEmpty,
        reason: 'wizardProtectPrivacy',
      );
      expect(l.wizardQuizzes, isNotEmpty, reason: 'wizardQuizzes');
      expect(l.wizardSafeBrowsing, isNotEmpty, reason: 'wizardSafeBrowsing');
      expect(l.wizardTV, isNotEmpty, reason: 'wizardTV');
      expect(l.wizardTikTok, isNotEmpty, reason: 'wizardTikTok');
      expect(l.wizardTimeDedicate, isNotEmpty, reason: 'wizardTimeDedicate');
      expect(l.wizardTimeSage, isNotEmpty, reason: 'wizardTimeSage');
      expect(l.wizardVideos, isNotEmpty, reason: 'wizardVideos');
      expect(l.wizardWelcomeSage, isNotEmpty, reason: 'wizardWelcomeSage');
      expect(l.wizardWelcomeTitle, isNotEmpty, reason: 'wizardWelcomeTitle');
      expect(l.wizardWhatLearn, isNotEmpty, reason: 'wizardWhatLearn');
      expect(l.wizardWhatLearnSage, isNotEmpty, reason: 'wizardWhatLearnSage');
      expect(l.wizardWhyLearn, isNotEmpty, reason: 'wizardWhyLearn');
      expect(l.wizardWhyLearnSage, isNotEmpty, reason: 'wizardWhyLearnSage');
      expect(l.wizardYouTube, isNotEmpty, reason: 'wizardYouTube');
      expect(l.xpLevelUp, isNotEmpty, reason: 'xpLevelUp');
      expect(l.chatTypingIndicator, isNotEmpty, reason: 'chatTypingIndicator');
      expect(l.demoModeOffline, isNotEmpty, reason: 'demoModeOffline');
      expect(l.streakFlame, isNotEmpty, reason: 'streakFlame');
      expect(l.tapToContinue, isNotEmpty, reason: 'tapToContinue');
      expect(l.exitQuizTitle, isNotEmpty, reason: 'exitQuizTitle');
      expect(l.exitQuizContent, isNotEmpty, reason: 'exitQuizContent');
      expect(l.activityMap30Days, isNotEmpty, reason: 'activityMap30Days');
      expect(l.miniGameExitTitle, isNotEmpty, reason: 'miniGameExitTitle');
      expect(l.miniGameExitContent, isNotEmpty, reason: 'miniGameExitContent');
      expect(l.paymentCancelTitle, isNotEmpty, reason: 'paymentCancelTitle');
      expect(
        l.paymentCancelContent,
        isNotEmpty,
        reason: 'paymentCancelContent',
      );
      expect(l.storeNewChestHint, isNotEmpty, reason: 'storeNewChestHint');
      expect(l.profilePhoto, isNotEmpty, reason: 'profilePhoto');
      expect(
        l.gemRainAnimationLabel,
        isNotEmpty,
        reason: 'gemRainAnimationLabel',
      );
      expect(l.exitQuizLabel, isNotEmpty, reason: 'exitQuizLabel');
      expect(
        l.shopItemFocusElixirName,
        isNotEmpty,
        reason: 'shopItemFocusElixirName',
      );
      expect(
        l.shopItemFocusElixirDesc,
        isNotEmpty,
        reason: 'shopItemFocusElixirDesc',
      );
      expect(l.shopItemXpBoostName, isNotEmpty, reason: 'shopItemXpBoostName');
      expect(l.shopItemXpBoostDesc, isNotEmpty, reason: 'shopItemXpBoostDesc');
      expect(
        l.shopItemLuckBoostName,
        isNotEmpty,
        reason: 'shopItemLuckBoostName',
      );
      expect(
        l.shopItemLuckBoostDesc,
        isNotEmpty,
        reason: 'shopItemLuckBoostDesc',
      );
      expect(
        l.shopItemSageMonocleName,
        isNotEmpty,
        reason: 'shopItemSageMonocleName',
      );
      expect(
        l.shopItemSageMonocleDesc,
        isNotEmpty,
        reason: 'shopItemSageMonocleDesc',
      );
      expect(
        l.shopItemTimeWarpName,
        isNotEmpty,
        reason: 'shopItemTimeWarpName',
      );
      expect(
        l.shopItemTimeWarpDesc,
        isNotEmpty,
        reason: 'shopItemTimeWarpDesc',
      );
      expect(
        l.shopItemTitaniumShieldName,
        isNotEmpty,
        reason: 'shopItemTitaniumShieldName',
      );
      expect(
        l.shopItemTitaniumShieldDesc,
        isNotEmpty,
        reason: 'shopItemTitaniumShieldDesc',
      );
      expect(
        l.shopItemPhoenixFeatherName,
        isNotEmpty,
        reason: 'shopItemPhoenixFeatherName',
      );
      expect(
        l.shopItemPhoenixFeatherDesc,
        isNotEmpty,
        reason: 'shopItemPhoenixFeatherDesc',
      );
      expect(
        l.shopItemNeonFrameName,
        isNotEmpty,
        reason: 'shopItemNeonFrameName',
      );
      expect(
        l.shopItemNeonFrameDesc,
        isNotEmpty,
        reason: 'shopItemNeonFrameDesc',
      );
      expect(
        l.shopItemGalaxyFrameName,
        isNotEmpty,
        reason: 'shopItemGalaxyFrameName',
      );
      expect(
        l.shopItemGalaxyFrameDesc,
        isNotEmpty,
        reason: 'shopItemGalaxyFrameDesc',
      );
      expect(
        l.shopItemDragonFrameName,
        isNotEmpty,
        reason: 'shopItemDragonFrameName',
      );
      expect(
        l.shopItemDragonFrameDesc,
        isNotEmpty,
        reason: 'shopItemDragonFrameDesc',
      );
      expect(
        l.shopItemCrystalFrameName,
        isNotEmpty,
        reason: 'shopItemCrystalFrameName',
      );
      expect(
        l.shopItemCrystalFrameDesc,
        isNotEmpty,
        reason: 'shopItemCrystalFrameDesc',
      );
      expect(
        l.shopItemSkullFrameName,
        isNotEmpty,
        reason: 'shopItemSkullFrameName',
      );
      expect(
        l.shopItemSkullFrameDesc,
        isNotEmpty,
        reason: 'shopItemSkullFrameDesc',
      );
      expect(
        l.shopItemTitleStormBreakerName,
        isNotEmpty,
        reason: 'shopItemTitleStormBreakerName',
      );
      expect(
        l.shopItemTitleStormBreakerDesc,
        isNotEmpty,
        reason: 'shopItemTitleStormBreakerDesc',
      );
      expect(
        l.shopItemTitleCyberSageName,
        isNotEmpty,
        reason: 'shopItemTitleCyberSageName',
      );
      expect(
        l.shopItemTitleCyberSageDesc,
        isNotEmpty,
        reason: 'shopItemTitleCyberSageDesc',
      );
      expect(
        l.shopItemTitleShadowHackerName,
        isNotEmpty,
        reason: 'shopItemTitleShadowHackerName',
      );
      expect(
        l.shopItemTitleShadowHackerDesc,
        isNotEmpty,
        reason: 'shopItemTitleShadowHackerDesc',
      );
      expect(
        l.shopItemTitleNightGuardianName,
        isNotEmpty,
        reason: 'shopItemTitleNightGuardianName',
      );
      expect(
        l.shopItemTitleNightGuardianDesc,
        isNotEmpty,
        reason: 'shopItemTitleNightGuardianDesc',
      );
      expect(
        l.shopItemTitleDigitalPhoenixName,
        isNotEmpty,
        reason: 'shopItemTitleDigitalPhoenixName',
      );
      expect(
        l.shopItemTitleDigitalPhoenixDesc,
        isNotEmpty,
        reason: 'shopItemTitleDigitalPhoenixDesc',
      );
      expect(
        l.shopItemEffectDigitalRainName,
        isNotEmpty,
        reason: 'shopItemEffectDigitalRainName',
      );
      expect(
        l.shopItemEffectDigitalRainDesc,
        isNotEmpty,
        reason: 'shopItemEffectDigitalRainDesc',
      );
      expect(
        l.shopItemEffectFireTrailName,
        isNotEmpty,
        reason: 'shopItemEffectFireTrailName',
      );
      expect(
        l.shopItemEffectFireTrailDesc,
        isNotEmpty,
        reason: 'shopItemEffectFireTrailDesc',
      );
      expect(
        l.shopItemThemeBlueName,
        isNotEmpty,
        reason: 'shopItemThemeBlueName',
      );
      expect(
        l.shopItemThemeBlueDesc,
        isNotEmpty,
        reason: 'shopItemThemeBlueDesc',
      );
      expect(
        l.shopItemThemePurpleName,
        isNotEmpty,
        reason: 'shopItemThemePurpleName',
      );
      expect(
        l.shopItemThemePurpleDesc,
        isNotEmpty,
        reason: 'shopItemThemePurpleDesc',
      );
      expect(
        l.shopItemThemeDarkFireName,
        isNotEmpty,
        reason: 'shopItemThemeDarkFireName',
      );
      expect(
        l.shopItemThemeDarkFireDesc,
        isNotEmpty,
        reason: 'shopItemThemeDarkFireDesc',
      );
      expect(
        l.shopItemThemeCyberNeonName,
        isNotEmpty,
        reason: 'shopItemThemeCyberNeonName',
      );
      expect(
        l.shopItemThemeCyberNeonDesc,
        isNotEmpty,
        reason: 'shopItemThemeCyberNeonDesc',
      );
      expect(
        l.mission3QueriesTitle,
        isNotEmpty,
        reason: 'mission3QueriesTitle',
      );
      expect(l.mission3QueriesDesc, isNotEmpty, reason: 'mission3QueriesDesc');
      expect(
        l.missionConstantProtectorTitle,
        isNotEmpty,
        reason: 'missionConstantProtectorTitle',
      );
      expect(
        l.missionConstantProtectorDesc,
        isNotEmpty,
        reason: 'missionConstantProtectorDesc',
      );
      expect(
        l.sageDailyLimitReached,
        isNotEmpty,
        reason: 'sageDailyLimitReached',
      );
      expect(l.sageConnectionWeak, isNotEmpty, reason: 'sageConnectionWeak');
      expect(l.gemHistoryTitle, isNotEmpty, reason: 'gemHistoryTitle');
      expect(l.gemHistoryEmpty, isNotEmpty, reason: 'gemHistoryEmpty');
      expect(l.gemHistoryJustNow, isNotEmpty, reason: 'gemHistoryJustNow');
      expect(l.gemHistoryYesterday, isNotEmpty, reason: 'gemHistoryYesterday');
      expect(l.gemReasonLesson, isNotEmpty, reason: 'gemReasonLesson');
      expect(
        l.gemReasonPerfectLesson,
        isNotEmpty,
        reason: 'gemReasonPerfectLesson',
      );
      expect(
        l.gemReasonFirstLesson,
        isNotEmpty,
        reason: 'gemReasonFirstLesson',
      );
      expect(l.gemReasonDailyBonus, isNotEmpty, reason: 'gemReasonDailyBonus');
      expect(
        l.gemReasonStreakMilestone,
        isNotEmpty,
        reason: 'gemReasonStreakMilestone',
      );
      expect(
        l.gemReasonAchievement,
        isNotEmpty,
        reason: 'gemReasonAchievement',
      );
      expect(l.gemReasonMission, isNotEmpty, reason: 'gemReasonMission');
      expect(l.gemReasonShop, isNotEmpty, reason: 'gemReasonShop');
      expect(l.gemCapWarning, isNotEmpty, reason: 'gemCapWarning');
      expect(l.close, isNotEmpty, reason: 'close');
      expect(l.stop, isNotEmpty, reason: 'stop');
      expect(l.sageEmotionCalm, isNotEmpty, reason: 'sageEmotionCalm');
      expect(l.sageEmotionHappy, isNotEmpty, reason: 'sageEmotionHappy');
      expect(l.sageEmotionCurious, isNotEmpty, reason: 'sageEmotionCurious');
      expect(l.sageEmotionThinking, isNotEmpty, reason: 'sageEmotionThinking');
      expect(l.sageEmotionReading, isNotEmpty, reason: 'sageEmotionReading');
      expect(l.sageEmotionSerious, isNotEmpty, reason: 'sageEmotionSerious');
      expect(l.sageEmotionNeutral, isNotEmpty, reason: 'sageEmotionNeutral');
      expect(l.sageEmotionExcited, isNotEmpty, reason: 'sageEmotionExcited');
      expect(l.sageEmotionConfused, isNotEmpty, reason: 'sageEmotionConfused');
      expect(l.sageEmotionWorried, isNotEmpty, reason: 'sageEmotionWorried');
      expect(l.sageEmotionSadSoft, isNotEmpty, reason: 'sageEmotionSadSoft');
      expect(l.sageEmotionSad, isNotEmpty, reason: 'sageEmotionSad');
      expect(l.sageEmotionCrying, isNotEmpty, reason: 'sageEmotionCrying');
      expect(
        l.sageEmotionDepressed,
        isNotEmpty,
        reason: 'sageEmotionDepressed',
      );
      expect(l.sageEmotionAngry, isNotEmpty, reason: 'sageEmotionAngry');
      expect(l.sageEmotionFurious, isNotEmpty, reason: 'sageEmotionFurious');
      expect(l.sageEmotionShocked, isNotEmpty, reason: 'sageEmotionShocked');
      expect(l.sageEmotionSleepy, isNotEmpty, reason: 'sageEmotionSleepy');
      expect(
        l.sageEmotionWhistling,
        isNotEmpty,
        reason: 'sageEmotionWhistling',
      );
      expect(
        l.sageEmotionPointLeft,
        isNotEmpty,
        reason: 'sageEmotionPointLeft',
      );
      expect(
        l.sageEmotionPointRight,
        isNotEmpty,
        reason: 'sageEmotionPointRight',
      );
      expect(l.sageEmotionWink, isNotEmpty, reason: 'sageEmotionWink');
      expect(l.sageEmotionShy, isNotEmpty, reason: 'sageEmotionShy');
      expect(l.sageEmotionLaughing, isNotEmpty, reason: 'sageEmotionLaughing');
      expect(l.sageEmotionSinging, isNotEmpty, reason: 'sageEmotionSinging');
      expect(l.sageEmotionScared, isNotEmpty, reason: 'sageEmotionScared');
      expect(
        l.sageEmotionEmbarrassed,
        isNotEmpty,
        reason: 'sageEmotionEmbarrassed',
      );
      expect(l.sageEmotionAnnoyed, isNotEmpty, reason: 'sageEmotionAnnoyed');
      expect(
        l.sageEmotionUnmotivated,
        isNotEmpty,
        reason: 'sageEmotionUnmotivated',
      );
      expect(
        l.sageEmotionDistressed,
        isNotEmpty,
        reason: 'sageEmotionDistressed',
      );
      expect(
        l.sageEmotionAggressive,
        isNotEmpty,
        reason: 'sageEmotionAggressive',
      );
      expect(l.sageEmotionLol, isNotEmpty, reason: 'sageEmotionLol');
      expect(
        l.sageEmotionHappyWings,
        isNotEmpty,
        reason: 'sageEmotionHappyWings',
      );
      expect(
        l.sageEmotionExcitedWave,
        isNotEmpty,
        reason: 'sageEmotionExcitedWave',
      );
      expect(
        l.sageEmotionSurprisedWings,
        isNotEmpty,
        reason: 'sageEmotionSurprisedWings',
      );
      expect(
        l.sageEmotionCelebrating,
        isNotEmpty,
        reason: 'sageEmotionCelebrating',
      );
      expect(l.sageEmotionProud, isNotEmpty, reason: 'sageEmotionProud');
      expect(l.sageEmotionPanic, isNotEmpty, reason: 'sageEmotionPanic');
      expect(
        l.chatSuggestionHelpLesson,
        isNotEmpty,
        reason: 'chatSuggestionHelpLesson',
      );
      expect(
        l.chatSuggestionExplainConcept,
        isNotEmpty,
        reason: 'chatSuggestionExplainConcept',
      );
      expect(
        l.chatSuggestionQuizMe,
        isNotEmpty,
        reason: 'chatSuggestionQuizMe',
      );
      expect(l.copiedToClipboard, isNotEmpty, reason: 'copiedToClipboard');
      expect(l.messageFromYou, isNotEmpty, reason: 'messageFromYou');
      expect(l.messageFromSage, isNotEmpty, reason: 'messageFromSage');
      expect(l.defaultStudentName, isNotEmpty, reason: 'defaultStudentName');
      expect(
        l.challenge_streak_milestone_desc('count'),
        isNotEmpty,
        reason: 'challenge_streak_milestone_desc',
      );
      expect(
        l.gemMilestoneDesc('count'),
        isNotEmpty,
        reason: 'gemMilestoneDesc',
      );
      expect(
        l.chestOpenedTitle('type'),
        isNotEmpty,
        reason: 'chestOpenedTitle',
      );
      expect(l.chestTitle('type'), isNotEmpty, reason: 'chestTitle');
      expect(
        l.chestTreasureLabel('type'),
        isNotEmpty,
        reason: 'chestTreasureLabel',
      );
      expect(l.continueLesson('title'), isNotEmpty, reason: 'continueLesson');
      expect(
        l.correctAnswers('correct', 'total'),
        isNotEmpty,
        reason: 'correctAnswers',
      );
      expect(l.dot('number'), isNotEmpty, reason: 'dot');
      expect(
        l.firstLessonProgress('current', 'total'),
        isNotEmpty,
        reason: 'firstLessonProgress',
      );
      expect(l.goToLesson('title'), isNotEmpty, reason: 'goToLesson');
      expect(
        l.levelUpCelebrationLabel(1),
        isNotEmpty,
        reason: 'levelUpCelebrationLabel',
      );
      expect(l.lessonProgress('percent'), isNotEmpty, reason: 'lessonProgress');
      expect(
        l.lessonsCompleted('count'),
        isNotEmpty,
        reason: 'lessonsCompleted',
      );
      expect(l.reviewCardLabel('count'), isNotEmpty, reason: 'reviewCardLabel');
      expect(l.reviewDuePrompt('count'), isNotEmpty, reason: 'reviewDuePrompt');
      expect(l.lessonsLevel('level'), isNotEmpty, reason: 'lessonsLevel');
      expect(l.levelProgress('percent'), isNotEmpty, reason: 'levelProgress');
      expect(l.minutes('min'), isNotEmpty, reason: 'minutes');
      expect(l.passDaysLeft('count'), isNotEmpty, reason: 'passDaysLeft');
      expect(l.passLevel('level'), isNotEmpty, reason: 'passLevel');
      expect(
        l.passProgress('current', 'required'),
        isNotEmpty,
        reason: 'passProgress',
      );
      expect(
        l.passRewards('current', 'max'),
        isNotEmpty,
        reason: 'passRewards',
      );
      expect(
        l.paywallPackageLabel('label'),
        isNotEmpty,
        reason: 'paywallPackageLabel',
      );
      expect(
        l.paywallPackageSupporter('level'),
        isNotEmpty,
        reason: 'paywallPackageSupporter',
      );
      expect(
        l.paywallWhatsAppError('link'),
        isNotEmpty,
        reason: 'paywallWhatsAppError',
      );
      expect(
        l.paywallWhatsAppFallback('message'),
        isNotEmpty,
        reason: 'paywallWhatsAppFallback',
      );
      expect(
        l.profileLevelValue('level'),
        isNotEmpty,
        reason: 'profileLevelValue',
      );
      expect(l.xpValue(1), isNotEmpty, reason: 'xpValue');
      expect(l.questions('count'), isNotEmpty, reason: 'questions');
      expect(l.quizProgress('percent'), isNotEmpty, reason: 'quizProgress');
      expect(l.rankingPosition('rank'), isNotEmpty, reason: 'rankingPosition');
      expect(
        l.rankingFirstPlace('name', 'xp'),
        isNotEmpty,
        reason: 'rankingFirstPlace',
      );
      expect(
        l.rankingSecondPlace('name', 'xp'),
        isNotEmpty,
        reason: 'rankingSecondPlace',
      );
      expect(
        l.rankingThirdPlace('name', 'xp'),
        isNotEmpty,
        reason: 'rankingThirdPlace',
      );
      expect(l.rankingXpToTop50('xp'), isNotEmpty, reason: 'rankingXpToTop50');
      expect(
        l.rankingYourPosition('xp', 'rank'),
        isNotEmpty,
        reason: 'rankingYourPosition',
      );
      expect(
        l.rewardAdEarnedGems('gems'),
        isNotEmpty,
        reason: 'rewardAdEarnedGems',
      );
      expect(
        l.sessionCorrectAnswer('answer'),
        isNotEmpty,
        reason: 'sessionCorrectAnswer',
      );
      expect(
        l.sessionScore('correct', 'total'),
        isNotEmpty,
        reason: 'sessionScore',
      );
      expect(l.stageProgress('percent'), isNotEmpty, reason: 'stageProgress');
      expect(
        l.storeBuyItem('cost', 'item'),
        isNotEmpty,
        reason: 'storeBuyItem',
      );
      expect(
        l.storeConfirmMessage('cost', 'item'),
        isNotEmpty,
        reason: 'storeConfirmMessage',
      );
      expect(
        l.storeDailyChestReward('xp'),
        isNotEmpty,
        reason: 'storeDailyChestReward',
      );
      expect(
        l.storeNeedMoreGems('have', 'need', 'needed'),
        isNotEmpty,
        reason: 'storeNeedMoreGems',
      );
      expect(l.streakDays('count'), isNotEmpty, reason: 'streakDays');
      expect(l.streakDaysCount('count'), isNotEmpty, reason: 'streakDaysCount');
      expect(
        l.tutorLessonsProgress('completed', 'required'),
        isNotEmpty,
        reason: 'tutorLessonsProgress',
      );
      expect(
        l.tutorMotivationAlmost('count'),
        isNotEmpty,
        reason: 'tutorMotivationAlmost',
      );
      expect(
        l.tutorMotivationGood('count'),
        isNotEmpty,
        reason: 'tutorMotivationGood',
      );
      expect(
        l.verifyEmailMessage('email'),
        isNotEmpty,
        reason: 'verifyEmailMessage',
      );
      expect(l.xpReward('xp'), isNotEmpty, reason: 'xpReward');
      expect(
        l.currentStreakDays('count'),
        isNotEmpty,
        reason: 'currentStreakDays',
      );
      expect(
        l.courseProgressLabel('percent'),
        isNotEmpty,
        reason: 'courseProgressLabel',
      );
      expect(
        l.stageProgressLabel('percent'),
        isNotEmpty,
        reason: 'stageProgressLabel',
      );
      expect(l.collapseSession('title'), isNotEmpty, reason: 'collapseSession');
      expect(l.expandSession('title'), isNotEmpty, reason: 'expandSession');
      expect(
        l.livesRemainingLabel('count'),
        isNotEmpty,
        reason: 'livesRemainingLabel',
      );
      expect(l.resultXpGained('xp'), isNotEmpty, reason: 'resultXpGained');
      expect(
        l.resultAccuracyLabel('percent'),
        isNotEmpty,
        reason: 'resultAccuracyLabel',
      );
      expect(
        l.resultLivesLabel('count'),
        isNotEmpty,
        reason: 'resultLivesLabel',
      );
      expect(l.gemBalanceLabel('count'), isNotEmpty, reason: 'gemBalanceLabel');
      expect(l.wizardStepLabel('step'), isNotEmpty, reason: 'wizardStepLabel');
      expect(
        l.chestRewardShareText('items', 'type'),
        isNotEmpty,
        reason: 'chestRewardShareText',
      );
      expect(
        l.gemHistoryMinutesAgo('count'),
        isNotEmpty,
        reason: 'gemHistoryMinutesAgo',
      );
      expect(
        l.gemHistoryHoursAgo('count'),
        isNotEmpty,
        reason: 'gemHistoryHoursAgo',
      );
      expect(
        l.gemHistoryDaysAgo('count'),
        isNotEmpty,
        reason: 'gemHistoryDaysAgo',
      );
      expect(l.gemRewardEarned('count'), isNotEmpty, reason: 'gemRewardEarned');
    });
  }
}
