/**
 * SAGEN Question Bank Generator
 * Generates 16,785 cybersecurity education questions across 8 stages.
 * 
 * Usage: node tools/generate_questions.js
 * 
 * Reads curriculum from ./curriculum.js
 * Outputs to assets/content/questions_ac_stN.json
 */

const fs = require('fs');
const path = require('path');
const { CURRICULUM } = require('./curriculum.js');

// ════════════════════════════════════════════════════════════════
// TOPIC MAPPING: lesson topic → cybersecurity topic category
// ════════════════════════════════════════════════════════════════

const TOPIC_MAP = {
  // Stage 1 - Fundamentos de Cuentas Digitales
  que_es_cuenta_digital: 'cuentas_digitales',
  seguridad_cuenta: 'cuentas_digitales',
  cuentas_locales_vs_linea: 'cuentas_digitales',
  ejemplos_cuentas: 'cuentas_digitales',
  elementos_seguridad: 'cuentas_digitales',
  que_es_contrasena: 'contrasenas',
  importancia_contrasenas: 'contrasenas',
  contrasenas_fuertes_debiles: 'contrasenas',
  errores_contrasenas: 'contrasenas',
  recordar_contrasenas: 'contrasenas',
  reglas_contrasenas_seguras: 'contrasenas',
  numeros_y_simbolos: 'contrasenas',
  longitud_complejidad: 'contrasenas',
  contrasenas_memorables: 'contrasenas',
  evaluacion_fortaleza: 'contrasenas',
  riesgos_reutilizar: 'contrasenas',
  ataques_credenciales: 'contrasenas',
  propagacion_filtraciones: 'contrasenas',
  estrategias_unicas: 'contrasenas',
  intro_gestores: 'gestores_contrasenas',
  que_es_gestor: 'gestores_contrasenas',
  funcionamiento_gestor: 'gestores_contrasenas',
  ventajas_gestor: 'gestores_contrasenas',
  elegir_gestor: 'gestores_contrasenas',
  practica_gestor: 'gestores_contrasenas',
  preguntas_seguridad: 'recuperacion_cuentas',
  correo_recuperacion: 'recuperacion_cuentas',
  codigos_respaldo: 'recuperacion_cuentas',
  procesos_verificacion: 'recuperacion_cuentas',
  proteccion_acceso: 'recuperacion_cuentas',
  que_es_2fa: 'dos_factores',
  metodos_segundo_factor: 'dos_factores',
  auth_sms: 'dos_factores',
  apps_autenticacion: 'dos_factores',
  passkeys: 'dos_factores',
  cuentas_vinculadas: 'cuentas_vinculadas',
  riesgos_vinculadas: 'cuentas_vinculadas',
  separar_cuentas: 'cuentas_vinculadas',
  correos_multiples: 'cuentas_vinculadas',
  gestion_cuentas: 'cuentas_vinculadas',
  que_es_phishing: 'phishing',
  correos_sospechosos: 'phishing',
  enlaces_peligrosos: 'phishing',
  adjuntos_maliciosos: 'phishing',
  proteccion_phishing: 'phishing',
  que_es_ingenieria_social: 'ingenieria_social',
  tacticas_manipulacion: 'ingenieria_social',
  llamadas_fraudulentas: 'ingenieria_social',
  proteccion_manipulacion: 'ingenieria_social',
  casos_reales_is: 'ingenieria_social',
  riesgos_dispositivos: 'dispositivos',
  navegacion_segura: 'navegacion_segura',
  modo_invitado: 'dispositivos',
  cierre_sesion_seguro: 'dispositivos',
  limpiar_historial: 'navegacion_segura',
  eval_crear_contrasena: 'contrasenas',
  eval_identificar_debiles: 'contrasenas',
  eval_errores: 'contrasenas',
  eval_escenarios: 'contrasenas',
  repaso_contrasenas: 'contrasenas',
  eval_detectar_phishing: 'phishing',
  eval_correos: 'phishing',
  eval_sitios_falsos: 'phishing',
  eval_ingenieria_social: 'ingenieria_social',
  repaso_proteccion: 'phishing',
  navegadores_seguros: 'navegacion_segura',
  cookies_rastreadores: 'navegacion_segura',
  historial_navegacion: 'navegacion_segura',
  modo_privado: 'navegacion_segura',
  extensiones_seguridad: 'navegacion_segura',
  que_es_wifi: 'wifi_vpn',
  riesgos_wifi_publico: 'wifi_vpn',
  proteccion_wifi_publico: 'wifi_vpn',
  config_router: 'wifi_vpn',
  intro_vpn: 'wifi_vpn',
  que_es_vpn: 'wifi_vpn',
  funcionamiento_vpn: 'wifi_vpn',
  cuando_usar_vpn: 'wifi_vpn',
  elegir_vpn: 'wifi_vpn',
  limites_vpn: 'wifi_vpn',
  importancia_actualizaciones: 'actualizaciones',
  tipos_actualizaciones: 'actualizaciones',
  automaticas_vs_manuales: 'actualizaciones',
  riesgos_no_actualizar: 'actualizaciones',
  practica_actualizaciones: 'actualizaciones',
  eval_navegacion: 'navegacion_segura',
  eval_wifi_vpn: 'wifi_vpn',
  eval_actualizaciones: 'actualizaciones',
  eval_escenarios_nav: 'navegacion_segura',
  repaso_navegacion: 'navegacion_segura',
  que_es_privacidad_linea: 'privacidad_linea',
  huella_digital: 'privacidad_linea',
  rastreo_internet: 'privacidad_linea',
  herramientas_privacidad: 'privacidad_linea',
  config_privacidad_navegador: 'privacidad_linea',
  info_revelada: 'redes_sociales',
  config_privacidad_rrss: 'redes_sociales',
  quien_ve_info: 'redes_sociales',
  publicaciones_seguras: 'redes_sociales',
  suplantacion_identidad: 'suplantacion_identidad',
  sitios_seguros: 'compras_linea',
  metodos_pago_seguros: 'compras_linea',
  verificar_url: 'compras_linea',
  facturas_digitales: 'compras_linea',
  deteccion_fraude_compras: 'compras_linea',
  eval_privacidad: 'privacidad_linea',
  eval_rrss: 'redes_sociales',
  eval_compras: 'compras_linea',
  eval_escenarios_priv: 'privacidad_linea',
  repaso_privacidad: 'privacidad_linea',
  seguridad_correo: 'correo_electronico',
  cifrado_correo: 'correo_electronico',
  deteccion_spam: 'correo_electronico',
  config_seguridad_correo: 'correo_electronico',
  gestion_bandeja: 'correo_electronico',
  por_que_eliminar: 'eliminacion_datos',
  donde_se_almacenan: 'eliminacion_datos',
  solicitudes_eliminacion: 'eliminacion_datos',
  eliminar_cuentas_antiguas: 'eliminacion_datos',
  derecho_olvido: 'derechos_digitales',
  dispositivos_inteligentes: 'iot',
  seguridad_router: 'wifi_vpn',
  redes_invitados: 'wifi_vpn',
  camaras_seguridad: 'iot',
  proteccion_iot: 'iot',
  repaso_phishing: 'phishing',
  repaso_navegacion_redes: 'navegacion_segura',
  repaso_privacidad_datos: 'privacidad_linea',
  repaso_integrado: 'cuentas_digitales',
  examen_cuentas: 'cuentas_digitales',
  examen_phishing: 'phishing',
  examen_navegacion: 'navegacion_segura',
  examen_privacidad: 'privacidad_linea',
  certificacion: 'cuentas_digitales',
  // Stage 2
  config_inicial_segura: 'dispositivos',
  bloqueo_pantalla: 'dispositivos',
  perfiles_usuario: 'dispositivos',
  cifrado_dispositivo: 'encriptacion',
  localizacion_recuperacion: 'dispositivos',
  practica_config_dispositivo: 'dispositivos',
  importancia_updates: 'actualizaciones',
  updates_sistema: 'actualizaciones',
  updates_apps: 'actualizaciones',
  parches_seguridad: 'actualizaciones',
  riesgos_desactualizado: 'actualizaciones',
  automatizacion_updates: 'actualizaciones',
  que_es_malware: 'malware',
  tipos_malware: 'malware',
  como_se_infecta: 'malware',
  antivirus: 'malware',
  senales_infeccion: 'malware',
  practica_proteccion: 'malware',
  que_es_backup: 'copias_seguridad',
  tipos_backup: 'copias_seguridad',
  local_vs_nube: 'copias_seguridad',
  regla_321: 'copias_seguridad',
  recuperacion_datos: 'copias_seguridad',
  practica_backup: 'copias_seguridad',
  riesgos_compartidos: 'dispositivos',
  compus_publicas: 'dispositivos',
  perfiles_invitado: 'dispositivos',
  cierre_sesion: 'dispositivos',
  limpieza_datos: 'dispositivos',
  practica_compartido: 'dispositivos',
  eval_config: 'dispositivos',
  eval_amenazas: 'malware',
  eval_proteccion: 'dispositivos',
  eval_backup: 'copias_seguridad',
  eval_escenarios_dev: 'dispositivos',
  repaso_dispositivos: 'dispositivos',
  seguridad_windows: 'sistemas_operativos',
  seguridad_macos: 'sistemas_operativos',
  seguridad_android: 'sistemas_operativos',
  seguridad_ios: 'sistemas_operativos',
  seguridad_linux: 'sistemas_operativos',
  comparacion_sos: 'sistemas_operativos',
  que_es_firewall: 'cortafuegos',
  firewall_software: 'cortafuegos',
  firewall_hardware: 'cortafuegos',
  reglas_firewall: 'cortafuegos',
  monitoreo_trafico: 'cortafuegos',
  practica_firewall: 'cortafuegos',
  que_es_encriptacion: 'encriptacion',
  encriptacion_disco: 'encriptacion',
  encriptacion_archivos: 'encriptacion',
  encriptacion_movil: 'encriptacion',
  herramientas_encriptacion: 'encriptacion',
  practica_encriptacion: 'encriptacion',
  tipos_cuentas: 'dispositivos',
  permisos_privilegios: 'dispositivos',
  admin_vs_usuario: 'dispositivos',
  gestion_multiples: 'dispositivos',
  proteccion_cuentas: 'dispositivos',
  practica_cuentas: 'dispositivos',
  eval_sos: 'sistemas_operativos',
  eval_firewall: 'cortafuegos',
  eval_encriptacion: 'encriptacion',
  eval_cuentas_usuario: 'dispositivos',
  eval_escenarios_sos: 'sistemas_operativos',
  repaso_sistema: 'sistemas_operativos',
  borrar_no_suficiente: 'eliminacion_datos',
  metodos_eliminacion: 'eliminacion_datos',
  software_eliminacion: 'eliminacion_datos',
  reciclaje_dispositivos: 'eliminacion_datos',
  destruccion_fisica: 'eliminacion_datos',
  practica_eliminacion: 'eliminacion_datos',
  que_es_nube: 'almacenamiento_nube',
  servicios_nube: 'almacenamiento_nube',
  seguridad_nube: 'almacenamiento_nube',
  privacidad_nube: 'almacenamiento_nube',
  sincronizacion_segura: 'almacenamiento_nube',
  practica_nube: 'almacenamiento_nube',
  eval_eliminacion: 'eliminacion_datos',
  eval_nube: 'almacenamiento_nube',
  eval_reciclaje: 'eliminacion_datos',
  eval_escenarios_nube: 'almacenamiento_nube',
  repaso_eliminacion_nube: 'eliminacion_datos',
  eval_practica_nube: 'almacenamiento_nube',
  amenazas_moviles: 'dispositivos',
  config_android: 'sistemas_operativos',
  config_ios: 'sistemas_operativos',
  proteccion_robo: 'dispositivos',
  seguridad_tablets: 'dispositivos',
  practica_movil: 'dispositivos',
  fuentes_seguras: 'dispositivos',
  permisos_apps: 'dispositivos',
  apps_falsas: 'malware',
  actualizacion_apps: 'actualizaciones',
  desinstalacion_segura: 'dispositivos',
  practica_evaluar_apps: 'dispositivos',
  eval_config_movil: 'dispositivos',
  eval_apps_seguras: 'dispositivos',
  eval_proteccion_robo: 'dispositivos',
  eval_escenarios_movil: 'dispositivos',
  repaso_movil: 'dispositivos',
  eval_practica_movil: 'dispositivos',
  que_es_iot: 'iot',
  amenazas_iot: 'iot',
  config_iot: 'iot',
  camaras_inteligentes: 'iot',
  asistentes_voz: 'iot',
  practica_iot: 'iot',
  backup_incremental: 'copias_seguridad',
  backup_diferencial: 'copias_seguridad',
  automatizacion_backup: 'copias_seguridad',
  verificacion_backup: 'copias_seguridad',
  prueba_recuperacion: 'copias_seguridad',
  practica_backup_auto: 'copias_seguridad',
  eval_iot: 'iot',
  eval_backups: 'copias_seguridad',
  eval_escenarios_iot: 'iot',
  eval_recuperacion: 'copias_seguridad',
  repaso_iot_backups: 'iot',
  eval_final_practica: 'dispositivos',
  repaso_config: 'dispositivos',
  repaso_malware: 'malware',
  repaso_backups: 'copias_seguridad',
  repaso_eliminacion: 'eliminacion_datos',
  repaso_integrado_dev: 'dispositivos',
  eval_repaso: 'dispositivos',
  examen_config: 'dispositivos',
  examen_malware: 'malware',
  examen_backup: 'copias_seguridad',
  examen_iot_movil: 'iot',
  certificacion_dev: 'dispositivos',
  eval_practica_final: 'dispositivos',
};

// Assign remaining topics generically
for (let i = 0; i < 200; i++) {
  const t = `topic_st3_${i}`;
  if (!TOPIC_MAP[t]) TOPIC_MAP[t] = 'derechos_digitales';
}
for (let i = 0; i < 150; i++) {
  const t = `topic_st4_${i}`;
  if (!TOPIC_MAP[t]) TOPIC_MAP[t] = 'privacidad_linea';
}
for (let i = 0; i < 145; i++) {
  const t = `topic_st5_${i}`;
  if (!TOPIC_MAP[t]) TOPIC_MAP[t] = 'dispositivos';
}
for (let i = 0; i < 120; i++) {
  const t = `topic_st6_${i}`;
  if (!TOPIC_MAP[t]) TOPIC_MAP[t] = 'seguridad_empresarial';
}
for (let i = 0; i < 125; i++) {
  const t = `topic_st7_${i}`;
  if (!TOPIC_MAP[t]) TOPIC_MAP[t] = 'amenazas_avanzadas';
}
for (let i = 0; i < 168; i++) {
  const t = `topic_st8_${i}`;
  if (!TOPIC_MAP[t]) TOPIC_MAP[t] = 'seguridad_empresarial';
}
